## Kite API

### Connect to Kite API

* Get Kite Connect API Subscrption
* Fetch the Kite Connect API KEY & API SECRET
* Use the URL to login & get the REDIRECT URL
* Connect to the Kite session

In [2]:
#!pip install --upgrade kiteconnect
#!pip install pandas

In [40]:
import pandas as pd
from datetime import datetime
import json
import time
from datetime import datetime, timedelta, time
import pandas as pd
import re

In [41]:
API_KEY = "ynacybo7nnsvhxfv"
API_SECRET = "uzmmqg2rlwz9le8nnkvf158prcq5btv9"

In [42]:
import logging
from kiteconnect import KiteConnect

logging.basicConfig(level=logging.DEBUG)

kite = KiteConnect(api_key=API_KEY)

kite.login_url()

# Redirect the user to the login url obtained
# from kite.login_url(), and receive the request_token
# from the registered redirect url after the login flow.
# Once you have the request_token, obtain the access_token
# as follows.

'https://kite.trade/connect/login?api_key=ynacybo7nnsvhxfv&v=3'

In [62]:
# replace with actual redirect URL
REDIRECT_URL = "http://127.0.0.1:8000/?action=login&type=login&status=success&request_token=Srb3pnmk21KqmeI3d33PuVnIB9tWg3rT"

In [63]:
import requests
import hashlib

# Example code to extract request_token from redirect URL (replace with your actual implementation)
request_token = REDIRECT_URL.split("request_token=")[1].split("&")[0]
print(f"Request Token: {request_token}")

session_url = "https://kite.zerodha.com/session/token"
checksum = hashlib.sha256(f"{API_KEY}{request_token}{API_SECRET}".encode()).hexdigest()
data = {"request_token": request_token, "checksum": checksum}

REQUEST_TOKEN = data['request_token']

try:
    data = kite.generate_session(REQUEST_TOKEN, api_secret=API_SECRET)
    print("Kite session generated successfully.")
except requests.exceptions.RequestException as e:
    print(f"Error generating access token: {e}")

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "POST /session/token HTTP/1.1" 200 None

Request Token: Srb3pnmk21KqmeI3d33PuVnIB9tWg3rT
Kite session generated successfully.

### API Data

* The API will give data about the instruments & the historical data

In [252]:
instrumentList = pd.read_csv("https://api.kite.trade/instruments")

In [253]:
instrumentList

,instrument_token,exchange_token,tradingsymbol,name,last_price,expiry,strike,tick_size,lot_size,instrument_type,segment,exchange
0,215681797,842507,BANKEX25SEPFUT,BANKEX,0,2025-09-25,0.0,0.05,30,FUT,BFO-FUT,BFO
1,220537093,861473,BANKEX25OCTFUT,BANKEX,0,2025-10-30,0.0,0.05,30,FUT,BFO-FUT,BFO
2,215645189,842364,SENSEX25SEPFUT,SENSEX,0,2025-09-25,0.0,0.05,20,FUT,BFO-FUT,BFO
3,220514309,861384,SENSEX25OCTFUT,SENSEX,0,2025-10-30,0.0,0.05,20,FUT,BFO-FUT,BFO
4,215835653,843108,SENSEX5025SEPFUT,SENSEX50,0,2025-09-25,0.0,0.05,75,FUT,BFO-FUT,BFO
...,...,...,...,...,...,...,...,...,...,...,...,...
90576,194418177,759446,12AFIL27-N0,NaN,0,NaN,0.0,0.01,1,EQ,NSE,NSE
90577,194418689,759448,SHREEJISPG,SHREEJI SHIPPING GLOBAL L,0,NaN,0.0,0.05,1,EQ,NSE,NSE
90578,194419969,759453,VIKRAMSOLR,VIKRAM SOLAR,0,NaN,0.0,0.05,1,EQ,NSE,NSE
90579,194421249,759458,GROWWNXT50,GROWWAMC - GROWWNXT50,0,NaN,0.0,0.01,1,EQ,NSE,NSE
90580,194422017,759461,GEMAROMA,GEM AROMATICS,0,NaN,0.0,0.05,1,EQ,NSE,NSE

In [254]:
instrumentList['segment'].unique()

array(['BFO-FUT', 'BFO-OPT', 'BSE', 'CDS-FUT', 'CDS-OPT', 'INDICES',
       'MCX-FUT', 'MCX-OPT', 'NCO', 'NCO-FUT', 'NCO-OPT', 'NFO-FUT',
       'NFO-OPT', 'NSE'], dtype=object)

In [257]:
nifty_op = instrumentList[(instrumentList['exchange']=='NFO') 
               & (instrumentList['segment']=='NFO-OPT') 
               & (instrumentList['tradingsymbol'].str.contains('NIFTY'))
               & (instrumentList['expiry'].str.contains('2025-08-14'))] 

# Add a new column 'exchange_tradingsymbol_key' to instrumentList
instrumentList['key'] = list(zip(instrumentList['exchange'], instrumentList['tradingsymbol']))

nifty_op.head()

,instrument_token,exchange_token,tradingsymbol,name,last_price,expiry,strike,tick_size,lot_size,instrument_type,segment,exchange,key
51492,11389954,44492,NIFTY2581424600CE,NIFTY,0,2025-08-14,24600.0,0.05,75,CE,NFO-OPT,NFO,"(NFO, NIFTY2581424600CE)"
51493,11390210,44493,NIFTY2581424600PE,NIFTY,0,2025-08-14,24600.0,0.05,75,PE,NFO-OPT,NFO,"(NFO, NIFTY2581424600PE)"
51494,11389442,44490,NIFTY2581424550CE,NIFTY,0,2025-08-14,24550.0,0.05,75,CE,NFO-OPT,NFO,"(NFO, NIFTY2581424550CE)"
51495,11389698,44491,NIFTY2581424550PE,NIFTY,0,2025-08-14,24550.0,0.05,75,PE,NFO-OPT,NFO,"(NFO, NIFTY2581424550PE)"
51496,11390978,44496,NIFTY2581424650CE,NIFTY,0,2025-08-14,24650.0,0.05,75,CE,NFO-OPT,NFO,"(NFO, NIFTY2581424650CE)"

In [411]:
instrumentList[(instrumentList['segment']=='INDICES')  ]

,instrument_token,exchange_token,tradingsymbol,name,last_price,expiry,strike,tick_size,lot_size,instrument_type,segment,exchange,key
29292,256265,1001,NIFTY 50,NIFTY 50,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,"(NSE, NIFTY 50)"
29293,265,1,SENSEX,SENSEX,0,NaN,0.0,0.0,0,EQ,INDICES,BSE,"(BSE, SENSEX)"
29294,256777,1003,NIFTY MIDCAP 100,NIFTY MIDCAP 100,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,"(NSE, NIFTY MIDCAP 100)"
29295,274441,1072,BANKEX,BSE INDEX BANKEX,0,NaN,0.0,0.0,0,EQ,INDICES,BSE,"(BSE, BANKEX)"
29296,260105,1016,NIFTY BANK,NIFTY BANK,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,"(NSE, NIFTY BANK)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29494,413961,1617,NIFTY IND DEFENCE,NIFTY INDIA DEFENCE,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,"(NSE, NIFTY IND DEFENCE)"
29495,414217,1618,NIFTY IND TOURISM,NIFTY INDIA TOURISM,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,"(NSE, NIFTY IND TOURISM)"
29496,414473,1619,NIFTY CAPITAL MKT,NIFTY CAPITAL MARKETS,0,NaN,0.0,0.0,0,EQ,INDICES,NSE,"(NSE, NIFTY CAPITAL MKT)"
29497,414729,1620,BSE1000,BSE 1000,0,NaN,0.0,0.0,0,EQ,INDICES,BSE,"(BSE, BSE1000)"
29498,414985,1621,BSE PSU BANK,BSE PSU BANK,0,NaN,0.0,0.0,0,EQ,INDICES,BSE,"(BSE, BSE PSU BANK)"

### Fetch data for Options

* Get the start date
* Fetching the open price of NIFTY on the start date
* Based on the open price, get the ATM strike and 20 strikes around ATM
* Generate trading symbols: CE above ATM, PE below ATM
* Fetch the historical data for the strikes

#### NIFTY Options

In [553]:
start = datetime(2025, 8, 13, 9, 15)     # This Friday

In [554]:
hist = kite.historical_data(256265, start, datetime(2025, 8, 13), interval="day") # NIFTY index token

# Convert to DataFrame
df_hist = pd.DataFrame(hist)

# Convert 'date' column to datetime if not already
df_hist['date'] = pd.to_datetime(df_hist['date'])

nifty_open = int(df_hist['open'][0])

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/256265/day?from=2025-08-13+09%3A15%3A00&to=2025-08-13+00%3A00%3A00&interval=day&continuous=0&oi=0 HTTP/1.1" 200 None

In [555]:
# 1. Get current spot price
symbol = 'NIFTY 50'
nifty_ltp = kite.quote('NSE:NIFTY 50')['NSE:NIFTY 50']['last_price']

print("---")
print(f"\nCurrent NIFTY LTP: {nifty_ltp}")
print(f"NIFTY Open on {start.date()}: {nifty_open}")

# 2. Calculate ATM and 20 strikes around
atm_strike = int(round(nifty_open / 50) * 50)

print(f"ATM Strike: {atm_strike}")

strike_range = [atm_strike + i*50 for i in range(-10, 11)]  # 20 strikes around ATM

# 3. Construct expiry symbol format for the weekly (Example for 14-Aug-2025)
expiry_dt = datetime(2025, 8, 14)
expiry_str = f"{expiry_dt.year % 100}{expiry_dt.month:d}{expiry_dt.day:02d}"  # '25814'

# 4. Generate trading symbols: CE above ATM, PE below ATM
trading_symbols = []
for strike in strike_range:
    if strike < atm_strike:
        trading_symbols.append(f"NIFTY{expiry_str}{strike}PE")
    elif strike > atm_strike:
        trading_symbols.append(f"NIFTY{expiry_str}{strike}CE")

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /quote?i=NSE%3ANIFTY+50 HTTP/1.1" 200 None

---

Current NIFTY LTP: 24980.65
NIFTY Open on 2025-08-13: 24586
ATM Strike: 24600

In [556]:
trading_symbols

['NIFTY2581424100PE',
 'NIFTY2581424150PE',
 'NIFTY2581424200PE',
 'NIFTY2581424250PE',
 'NIFTY2581424300PE',
 'NIFTY2581424350PE',
 'NIFTY2581424400PE',
 'NIFTY2581424450PE',
 'NIFTY2581424500PE',
 'NIFTY2581424550PE',
 'NIFTY2581424650CE',
 'NIFTY2581424700CE',
 'NIFTY2581424750CE',
 'NIFTY2581424800CE',
 'NIFTY2581424850CE',
 'NIFTY2581424900CE',
 'NIFTY2581424950CE',
 'NIFTY2581425000CE',
 'NIFTY2581425050CE',
 'NIFTY2581425100CE']

In [338]:
# 5. Load instrument list and map trading symbols to tokens
instrument_list = pd.DataFrame(kite.instruments('NFO'))

nifty_op = instrumentList[(instrumentList['exchange']=='NFO') 
               & (instrumentList['segment']=='NFO-OPT') 
               & (instrumentList['tradingsymbol'].str.contains('NIFTY'))
               & (instrumentList['expiry'].str.contains('2025-08-14')) &
               (instrumentList['tradingsymbol'].isin(trading_symbols))] 

# Add a new column 'exchange_tradingsymbol_key' to instrumentList
nifty_op['key'] = list(zip(nifty_op['exchange'], nifty_op['tradingsymbol']))

# Now build the token_map
token_map = {
    row['tradingsymbol']: row['instrument_token']
    for _, row in nifty_op.iterrows()
}

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/NFO HTTP/1.1" 200 405055
C:\Users\harip\AppData\Local\Temp\ipykernel_35704\2643342579.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nifty_op['key'] = list(zip(nifty_op['exchange'], nifty_op['tradingsymbol']))

In [339]:
token_map

{'NIFTY2581424600CE': 11389954,
 'NIFTY2581424650CE': 11390978,
 'NIFTY2581424500PE': 11385090,
 'NIFTY2581424700CE': 11391490,
 'NIFTY2581424450PE': 11384578,
 'NIFTY2581424750CE': 11392002,
 'NIFTY2581424400PE': 11384066,
 'NIFTY2581424800CE': 11393026,
 'NIFTY2581424350PE': 11383042,
 'NIFTY2581424850CE': 11393538,
 'NIFTY2581424300PE': 11382530,
 'NIFTY2581424900CE': 11394050,
 'NIFTY2581424250PE': 11382018,
 'NIFTY2581424950CE': 11394562,
 'NIFTY2581425050CE': 11395586,
 'NIFTY2581425000CE': 11395074,
 'NIFTY2581424200PE': 11381506,
 'NIFTY2581424150PE': 11380994,
 'NIFTY2581424100PE': 11380482,
 'NIFTY2581424050PE': 11379458}

In [361]:
start = datetime(2025, 8, 8, 9, 15)     # This Friday
end   = datetime(2025, 8, 14, 15, 30)   # Next Thursday

In [362]:
# Get tokens for only these symbols
tokens_to_fetch = {symbol: token_map.get(symbol) for symbol in trading_symbols}

all_hist_df = pd.DataFrame()

for symbol, token in tokens_to_fetch.items():
    if token is not None:
        try:
            hist = kite.historical_data(token, start, end, interval="5minute")
            df_hist = pd.DataFrame(hist)
            df_hist["symbol"] = symbol
            df_hist["token"] = token
            all_hist_df = pd.concat([all_hist_df, df_hist], ignore_index=True)
            time.sleep(0.5)  # To avoid rate limits
        except Exception as e:
            print(f"Error fetching data for {symbol}: {e}")
    else:
        print(f"Token not found for {symbol}")

display(all_hist_df)

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11379458/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11380482/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11380994/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11381506/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11382018/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11382530/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11383042/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11384066/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11384578/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11385090/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11389954/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11390978/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11391490/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11392002/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11393026/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11393538/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11394050/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11394562/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11395074/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/11395586/5minute?from=2025-08-08+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None

,date,open,high,low,close,volume,symbol,token
0,2025-08-08 09:15:00+05:30,16.00,16.00,12.55,14.90,893775,NIFTY2581424050PE,11379458
1,2025-08-08 09:20:00+05:30,14.90,16.15,14.20,15.60,685050,NIFTY2581424050PE,11379458
2,2025-08-08 09:25:00+05:30,15.60,20.80,15.05,20.80,948975,NIFTY2581424050PE,11379458
3,2025-08-08 09:30:00+05:30,20.75,22.00,19.15,21.15,706125,NIFTY2581424050PE,11379458
4,2025-08-08 09:35:00+05:30,21.15,23.45,18.10,19.05,873000,NIFTY2581424050PE,11379458
...,...,...,...,...,...,...,...,...
1595,2025-08-08 15:30:00+05:30,6.65,6.65,6.65,6.65,0,NIFTY2581425050CE,11395586
1596,2025-08-08 16:15:00+05:30,6.65,6.65,6.65,6.65,0,NIFTY2581425050CE,11395586
1597,2025-08-08 16:40:00+05:30,6.65,6.65,6.65,6.65,0,NIFTY2581425050CE,11395586
1598,2025-08-08 16:45:00+05:30,6.65,6.65,6.65,6.65,0,NIFTY2581425050CE,11395586
1599,2025-08-08 17:05:00+05:30,6.65,6.65,6.65,6.65,0,NIFTY2581425050CE,11395586

In [359]:
all_hist_df.to_csv("nifty_options_data.csv", index=False)

In [349]:
# List of instrument tokens for which we want quotes

token_map_sample =  token_map #dict(list(token_map.items())[:5])

tokens = list(token_map_sample.values())

# Fetch quotes (can pass a list of instrument tokens as strings or ints)
quotes = kite.quote(tokens)  # or kite.quote(tokens)

quotes_df = pd.DataFrame([
    {
        "symbol": symbol,
        "token": token,
        **quotes[str(token)]
    }
    for symbol, token in token_map_sample.items()
])

display(quotes_df)

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /quote?i=11389954&i=11390978&i=11385090&i=11391490&i=11384578&i=11392002&i=11384066&i=11393026&i=11383042&i=11393538&i=11382530&i=11394050&i=11382018&i=11394562&i=11395586&i=11395074&i=11381506&i=11380994&i=11380482&i=11379458 HTTP/1.1" 200 None

,symbol,token,instrument_token,timestamp,last_trade_time,last_price,last_quantity,buy_quantity,sell_quantity,volume,average_price,oi,oi_day_high,oi_day_low,net_change,lower_circuit_limit,upper_circuit_limit,ohlc,depth
0,NIFTY2581424600CE,11389954,11389954,2025-08-08 14:45:36,2025-08-08 14:45:35,69.10,75,897600,2831175,171153075,86.35,13580550,13666500,3075975,0,0.05,478.00,"{'open': 150, 'high': 160, 'low': 61.4, 'close...","{'buy': [{'price': 68.9, 'quantity': 2400, 'or..."
1,NIFTY2581424650CE,11390978,11390978,2025-08-08 14:45:35,2025-08-08 14:45:34,55.05,150,3064125,925725,65986650,68.91,4400925,4400925,993375,0,0.05,431.20,"{'open': 128, 'high': 128, 'low': 49.05, 'clos...","{'buy': [{'price': 55, 'quantity': 2475, 'orde..."
2,NIFTY2581424500PE,11385090,11385090,2025-08-08 14:45:35,2025-08-08 14:45:34,153.80,150,2865900,602175,235862625,137.66,6512625,10150050,4626675,0,0.05,531.60,"{'open': 84, 'high': 174, 'low': 81, 'close': ...","{'buy': [{'price': 153.5, 'quantity': 525, 'or..."
3,NIFTY2581424700CE,11391490,11391490,2025-08-08 14:45:35,2025-08-08 14:45:34,43.75,75,3034650,1623225,110810175,54.45,9509850,10633275,2872500,0,0.05,383.50,"{'open': 100, 'high': 104.85, 'low': 39.1, 'cl...","{'buy': [{'price': 43.55, 'quantity': 2925, 'o..."
4,NIFTY2581424450PE,11384578,11384578,2025-08-08 14:45:35,2025-08-08 14:45:35,127.65,450,3504675,585975,193880775,120.04,3850500,4755075,1200975,0,0.05,482.90,"{'open': 69.4, 'high': 146.95, 'low': 66.7, 'c...","{'buy': [{'price': 127.35, 'quantity': 1350, '..."
5,NIFTY2581424750CE,11392002,11392002,2025-08-08 14:45:35,2025-08-08 14:45:35,34.40,75,3100575,569775,51497175,43.41,3777150,4086150,988800,0,0.05,342.30,"{'open': 72, 'high': 77.5, 'low': 31, 'close':...","{'buy': [{'price': 34.4, 'quantity': 75, 'orde..."
6,NIFTY2581424400PE,11384066,11384066,2025-08-08 14:45:36,2025-08-08 14:45:35,105.20,150,4147125,1102575,262561425,100.14,7358325,8028225,3588750,0,0.05,436.25,"{'open': 59.3, 'high': 122, 'low': 53.65, 'clo...","{'buy': [{'price': 104.9, 'quantity': 525, 'or..."
7,NIFTY2581424800CE,11393026,11393026,2025-08-08 14:45:35,2025-08-08 14:45:35,27.30,75,3468825,1963125,99405600,33.83,9213900,9483375,3072675,0,0.05,302.95,"{'open': 54.75, 'high': 63.95, 'low': 24.65, '...","{'buy': [{'price': 27.2, 'quantity': 6450, 'or..."
8,NIFTY2581424350PE,11383042,11383042,2025-08-08 14:45:35,2025-08-08 14:45:34,85.75,75,3393150,478575,112253925,81.76,3094500,3274200,1523250,0,0.05,394.10,"{'open': 37.3, 'high': 101.4, 'low': 37.3, 'cl...","{'buy': [{'price': 85.6, 'quantity': 750, 'ord..."
9,NIFTY2581424850CE,11393538,11393538,2025-08-08 14:45:35,2025-08-08 14:45:32,21.55,600,3300375,419325,39044775,26.68,2769675,2844825,852600,0,0.05,268.30,"{'open': 47.8, 'high': 48.25, 'low': 19.7, 'cl...","{'buy': [{'price': 21.55, 'quantity': 8400, 'o..."
10,NIFTY2581424300PE,11382530,11382530,2025-08-08 14:45:35,2025-08-08 14:45:35,69.15,75,3441075,658950,131229375,65.64,5526000,5955300,2494800,0,0.05,353.15,"{'open': 40, 'high': 83.35, 'low': 34, 'close'...","{'buy': [{'price': 69.1, 'quantity': 2850, 'or..."
11,NIFTY2581424900CE,11394050,11394050,2025-08-08 14:45:36,2025-08-08 14:45:35,17.05,150,3298350,675750,60931425,20.81,5626800,6427200,2295075,0,0.05,235.60,"{'open': 45.65, 'high': 45.65, 'low': 15.6, 'c...","{'buy': [{'price': 17, 'quantity': 13575, 'ord..."
12,NIFTY2581424250PE,11382018,11382018,2025-08-08 14:45:36,2025-08-08 14:45:35,56.20,75,2933025,337275,64137600,53.18,2097525,2193225,809100,0,0.05,315.65,"{'open': 30, 'high': 68.25, 'low': 27.9, 'clos...","{'buy': [{'price': 55.95, 'quantity': 1725, 'o..."
13,NIFTY2581424950CE,11394562,11394562,2025-08-08 14:45:36,2025-08-08 14:45:35,13.75,75,2887125,349650,30490950,16.56,2130825,2183550,815925,0,0.05,207.50,"{'open': 30.2, 'high': 32.2, 'low': 12.7, 'clo...","{'buy': [{'price': 13.75, 'quantity': 6150, 'o..."
14,NIFTY2581425050CE,11395586,11395586,2025-08-08 14:45:35,2025-08-08 14:45:35,9.05,75,3229800,279900,24942375,10.21,2228775,2242350,675375,0,0.05,158.05,"{'open': 19.45, 'high': 19.45, 'low': 8.2, 'cl...","{'buy': [{'price': 9, 'quantity': 12900, 'orde..."
15,NIFTY2581425000CE,11395074,11395074,2025-08-08 14:45:36,2025-08-08 14:45:36,11.30,75,4416450,1494375,80348400,13.13,12690225,12799500,5340000,0,0.05,180.80,"{'open': 20, 'high': 27, 'low': 10.35, 'close'...","{'buy': [{'price': 11.25, 'quantity': 25125, '..."
16,NIFTY2581424200PE,11381506,11381506,2025-08-08 14:45:36,2025-08-08 14:45:34,45.50,75,3540300,498975,109234650,42.69,4358475,5326050,3283425,0,0.05,280.80,"{'open': 21.7, 'high': 55.75, 'low': 21.65, 'c...","{'buy': [{'price': 45.25, 'quantity': 2775, 'o..."
17,NIFTY2581424150PE,11380994,11380994,2025-08-08 14:45:35,2025-08-08 14:45:34,36.45,75,3248550,254850,47269275,35.25,1416900,1636950,568575,0,0.05,249.45,"{'open': 19.5, 'high': 45.5, 'low': 18.2, 'clo...","{'buy': [{'price': 36.45, 'quantity': 3375, 'o..."
18,NIFTY2581424100PE,11380482,11380482,2025-08-08 14:45:35,2025-08-08 14:45:35,29.55,75,3365250,343950,66618525,28.67,2502525,2885625,1328550,0,0.05,219.65,"{'open': 18.15, 'high': 37, 'low': 14.8, 'clos...","{'buy': [{'price': 29.55, 'quantity': 450, 'or..."
19,NIFTY2581424050PE,11379458,11379458,2025-08-08 14:45:36,2025-08-08 14:45:35,23.95,150,2910375,165300,35828175,23.50,1432050,1440900,656700,0,0.05,192.35,"{'open': 16, 'high': 30.3, 'low': 12.55, 'clos...","{'buy': [{'price': 23.95, 'quantity': 2850, 'o..."

#### Function to fetch NIFTY/SENSEX Options

### NIFTY

In [ ]:
def fetch_index_options_weekly_data(kite, index_symbol, start_date, end_date, expiry_date, interval="day", step=None):
    """
    Fetch index historical data (NIFTY 50 or SENSEX), determine ATM strike,
    generate option trading symbols for a given expiry, map them to instrument tokens,
    fetch their historical data, and get latest quotes.

    Parameters
    ----------
    kite : KiteConnect
        Initialized Kite Connect API client instance.
    index_symbol : str
        "SENSEX" or "NIFTY 50".
    start_date : datetime
        Start datetime for historical data.
    end_date : datetime
        End datetime for options historical data.
    expiry_date : datetime
        Expiry date for options trading symbols.
    interval : str, default "day"
        Candle interval for index historical data.
    step : int, optional
        Strike step size (default: 100 for Sensex, 50 for Nifty).

    Returns
    -------
    index_open : int
    index_ltp : float
    atm_strike : int
    token_map : dict
    all_hist_df : DataFrame
    quotes_df : DataFrame
    """

    # ----------------
    #  INDEX METADATA
    # ----------------
    index_map = {
        "SENSEX": {"token": 265, "exchange": "BSE", "step": 100, "opt_segment": "BFO"},
        "NIFTY 50": {"token": 256265, "exchange": "NSE", "step": 50, "opt_segment": "NFO"}
    }

    if index_symbol.upper() not in [key.upper() for key in index_map.keys()]:
        raise ValueError("Invalid index symbol. Use 'SENSEX' or 'NIFTY 50'")

    # Pick correct config
    for k, v in index_map.items():
        if k.upper() == index_symbol.upper():
            index_cfg = v
            index_symbol_std = k  # Standardized case
            break

    if step is None:
        step = index_cfg["step"]

    # ----------------
    # 1. Fetch Index Historical Data
    # ----------------
    hist = kite.historical_data(index_cfg["token"], start_date, start_date, interval="day")
    df_hist = pd.DataFrame(hist)
    df_hist['date'] = pd.to_datetime(df_hist['date'])
    index_open = int(df_hist['open'][0])

    # LTP of index
    full_symbol = f"{index_cfg['exchange']}:{index_symbol_std}"
    index_ltp = kite.quote(full_symbol)[full_symbol]['last_price']

    print("\n---")
    print(f"Current {index_symbol_std} LTP: {index_ltp}")
    print(f"{index_symbol_std} Open on {start_date.date()}: {index_open}")

    # ----------------
    # 2. ATM Calculation
    # ----------------
    atm_strike = int(round(index_open / step) * step)
    print(f"ATM Strike: {atm_strike}")

    # Strike Range
    strike_range = [atm_strike + i * step for i in range(-10, 11)]

    # ----------------
    # 3. Expiry String & Trading Symbols
    #    Exchange code format is different for NSE vs BSE
    # ----------------
    expiry_str_bse = f"{expiry_date.year % 100}{expiry_date.month:d}{expiry_date.day:02d}"  # e.g., 25814
    expiry_str_nse = f"{expiry_date.year % 100}{expiry_date.month:d}{expiry_date.day:02d}"  # '25814'


    trading_symbols = []
    for strike in strike_range:
        if index_cfg['exchange'] == 'BSE':  # SENSEX
            if strike < atm_strike:
                trading_symbols.append(f"{index_symbol_std}{expiry_str_bse}{strike}PE")
            elif strike > atm_strike:
                trading_symbols.append(f"{index_symbol_std}{expiry_str_bse}{strike}CE")
        else:  # NSE (NIFTY)
            # Force "NIFTY" instead of NIFTY50
            nse_opts_symbol_prefix = "NIFTY" if "NIFTY" in index_symbol_std.upper() else index_symbol_std.replace(' ', '')
            if strike < atm_strike:
                trading_symbols.append(f"{nse_opts_symbol_prefix}{expiry_str_nse}{strike}PE")
            elif strike > atm_strike:
                trading_symbols.append(f"{nse_opts_symbol_prefix}{expiry_str_nse}{strike}CE")

    # ----------------
    # 4. Map to Tokens
    # ----------------
    try:
        instruments_df = pd.DataFrame(kite.instruments(index_cfg["opt_segment"]))
        index_ops = instruments_df[
            (instruments_df['exchange'] == index_cfg["opt_segment"]) &
            (instruments_df['segment'] == f"{index_cfg['opt_segment']}-OPT") &
            (instruments_df['tradingsymbol'].isin(trading_symbols)) &
            (instruments_df['expiry'] == expiry_date.date())
        ]
        
        token_map = {
            row['tradingsymbol']: row['instrument_token']
            for _, row in index_ops.iterrows()
        }
        print("\nMapped Options Tokens:")
        print(token_map)
    except Exception as e:
        print("\nCould not fetch instruments or no options available.")
        print(str(e))
        token_map = {}

    # ----------------
    # 5. Historical Data for Options
    # ----------------
    market_close_time = time(15, 30)  # 3:30 PM IST
    if start_date.date() == end_date.date():
        if end_date.time() > market_close_time:
            end_date = datetime.combine(end_date.date(), market_close_time)

    all_hist_df = pd.DataFrame()
    for symbol, token in {s: token_map.get(s) for s in trading_symbols}.items():
        if token:
            try:
                hist = kite.historical_data(token, start_date, end_date, interval=interval)
                df_hist = pd.DataFrame(hist)
                df_hist["symbol"] = symbol
                df_hist["token"] = token
                all_hist_df = pd.concat([all_hist_df, df_hist], ignore_index=True)
            except Exception as e:
                print(f"Error fetching data for {symbol}: {e}")
        else:
            print(f"Token not found for {symbol}")

    # For intraday, filter out candles after market close (3:30 PM IST)
        all_hist_df['date'] = pd.to_datetime(all_hist_df['date'])
        market_close_time = time(15, 30)
        all_hist_df = all_hist_df[all_hist_df['date'].dt.time <= market_close_time]

    # ----------------
    # 6. Latest Quotes (Sample)
    # ----------------
    token_map_sample = dict(list(token_map.items())[:5])
    tokens = list(token_map_sample.values())
    if tokens:
        quotes = kite.quote(tokens)
        quotes_df = pd.DataFrame([
            {"symbol": sym, "token": tok, **quotes[str(tok)]}
            for sym, tok in token_map_sample.items()
        ])
    else:
        quotes_df = pd.DataFrame()

    # ----------------
    # 7. Summary
    # ----------------
    print(f"\nTotal option trading symbols generated: {len(trading_symbols)}")
    print(f"Total mapped tokens found: {len(token_map)}")
    print(f"Historical rows fetched for options: {len(all_hist_df)}")
    print(f"Sample quotes fetched: {len(quotes_df)}")

    return index_open, index_ltp, atm_strike, token_map, all_hist_df, quotes_df

In [37]:
def fetch_index_options_weekly_data(kite, index_symbol, start_date, end_date, expiry_date, interval="day", step=None):
    """
    Fetch index historical data (NIFTY 50 or SENSEX), determine ATM strike,
    generate option trading symbols (CE + PE for all strikes, including ATM),
    map them to instrument tokens, fetch their historical data, and get latest quotes.
    """
    import pandas as pd
    from datetime import datetime, time

    # ----------------
    # INDEX METADATA
    # ----------------
    index_map = {
        "SENSEX": {"token": 265, "exchange": "BSE", "step": 100, "opt_segment": "BFO"},
        "NIFTY 50": {"token": 256265, "exchange": "NSE", "step": 50, "opt_segment": "NFO"}
    }

    if index_symbol.upper() not in [key.upper() for key in index_map.keys()]:
        raise ValueError("Invalid index symbol. Use 'SENSEX' or 'NIFTY 50'")

    # Pick correct config
    for k, v in index_map.items():
        if k.upper() == index_symbol.upper():
            index_cfg = v
            index_symbol_std = k
            break

    if step is None:
        step = index_cfg["step"]

    # ----------------
    # 1. Fetch Index Historical Data
    # ----------------
    hist = kite.historical_data(index_cfg["token"], start_date, start_date, interval="day")
    df_hist = pd.DataFrame(hist)
    df_hist['date'] = pd.to_datetime(df_hist['date'])
    index_open = int(df_hist['open'][0])

    # LTP of index
    full_symbol = f"{index_cfg['exchange']}:{index_symbol_std}"
    index_ltp = kite.quote(full_symbol)[full_symbol]['last_price']

    print("\n---")
    print(f"Current {index_symbol_std} LTP: {index_ltp}")
    print(f"{index_symbol_std} Open on {start_date.date()}: {index_open}")

    # ----------------
    # 2. ATM Calculation
    # ----------------
    atm_strike = int(round(index_open / step) * step)
    print(f"ATM Strike: {atm_strike}")

    # Strike Range
    strike_range = [atm_strike + i * step for i in range(-50, 51)]

    # ----------------
    # 3. Expiry String & Trading Symbols
    # ----------------
    expiry_str_bse = f"{expiry_date.year % 100}{'O'}{expiry_date.day:02d}"  # e.g., 25814
    expiry_str_nse = f"{expiry_date.year % 100}{'O'}{expiry_date.day:02d}"  # '25814'


    trading_symbols = []
    for strike in strike_range:
        if index_cfg['exchange'] == 'BSE':  # SENSEX
            trading_symbols.append(f"{index_symbol_std}{expiry_str_bse}{strike}CE")
            trading_symbols.append(f"{index_symbol_std}{expiry_str_bse}{strike}PE")
        else:  # NSE (NIFTY)
            nse_opts_symbol_prefix = "NIFTY" if "NIFTY" in index_symbol_std.upper() else index_symbol_std.replace(' ', '')
            trading_symbols.append(f"{nse_opts_symbol_prefix}{expiry_str_nse}{strike}CE")
            trading_symbols.append(f"{nse_opts_symbol_prefix}{expiry_str_nse}{strike}PE")

    # ----------------
    # 4. Map to Tokens
    # ----------------
    try:
        instruments_df = pd.DataFrame(kite.instruments(index_cfg["opt_segment"]))
        index_ops = instruments_df[
            (instruments_df['exchange'] == index_cfg["opt_segment"]) &
            (instruments_df['segment'] == f"{index_cfg['opt_segment']}-OPT") &
            (instruments_df['tradingsymbol'].isin(trading_symbols)) &
            (instruments_df['expiry'] == expiry_date.date())
        ]
        
        token_map = {
            row['tradingsymbol']: row['instrument_token']
            for _, row in index_ops.iterrows()
        }
        print("\nMapped Options Tokens:")
        print(token_map)
    except Exception as e:
        print("\nCould not fetch instruments or no options available.")
        print(str(e))
        token_map = {}

    # ----------------
    # 5. Historical Data for Options
    # ----------------
    market_close_time = time(15, 30)
    if start_date.date() == end_date.date():
        if end_date.time() > market_close_time:
            end_date = datetime.combine(end_date.date(), market_close_time)

    all_hist_df = pd.DataFrame()
    for symbol, token in {s: token_map.get(s) for s in trading_symbols}.items():
        if token:
            try:
                hist = kite.historical_data(token, start_date, end_date, interval=interval)
                df_hist = pd.DataFrame(hist)
                df_hist["symbol"] = symbol
                df_hist["token"] = token
                all_hist_df = pd.concat([all_hist_df, df_hist], ignore_index=True)
            except Exception as e:
                print(f"Error fetching data for {symbol}: {e}")
        else:
            print(f"Token not found for {symbol}")

    # Filter candles after market close
    if not all_hist_df.empty:
        all_hist_df['date'] = pd.to_datetime(all_hist_df['date'])
        all_hist_df = all_hist_df[all_hist_df['date'].dt.time <= market_close_time]

    # ----------------
    # 6. Latest Quotes (sample subset)
    # ----------------
    token_map_sample = dict(list(token_map.items())[:5])
    tokens = list(token_map_sample.values())
    if tokens:
        quotes = kite.quote(tokens)
        quotes_df = pd.DataFrame([
            {"symbol": sym, "token": tok, **quotes[str(tok)]}
            for sym, tok in token_map_sample.items()
        ])
    else:
        quotes_df = pd.DataFrame()


    # ----------------
    # 7. Add Index Value (NIFTY/SENSEX) to all option candles
    # ----------------
    try:
        # Fetch intraday index historical data matching 'interval'
        index_hist = kite.historical_data(
            index_cfg["token"],
            start_date,
            end_date,
            interval=interval
        )
        df_index = pd.DataFrame(index_hist)
        df_index['date'] = pd.to_datetime(df_index['date'])
        df_index.rename(columns={'close': f'index_close'}, inplace=True)

        if not all_hist_df.empty:
            # Merge option candles with index value at same timestamp
            all_hist_df = pd.merge(
                all_hist_df,
                df_index[['date', f'index_close']],
                on="date",
                how="left"
            )
            print(f"\nAdded {index_symbol_std} values as a column to options dataframe.")
        else:
            print("\nOptions dataframe empty, skipping index merge.")

    except Exception as e:
        print(f"\nError adding {index_symbol_std} values to options dataframe: {e}")


    def parse_symbol(symbol):
        # Example symbol: NIFTY25AUG24800PE or NIFTY2581424800PE
        match = re.match(r'([A-Z]+)(\d{2}[A-Z]{3}|\d{5})(\d+)(CE|PE)', symbol)
        if match:
            index = match.group(1)
            expiry_raw = match.group(2)
            strike = match.group(3)
            option_type = match.group(4)
            # Format expiry month
            if len(expiry_raw) == 5:  # e.g., 25814
            #     year = "20" + expiry_raw[:2]
            #     month_num = int(expiry_raw[2])
            #     day = expiry_raw[3:]
            #     month = pd.to_datetime(f"{year}-{month_num}-01").strftime("%b").upper()
            #     expiry_month = f"{expiry_raw[:2]}-{month}-{day}"
            # else:  # e.g., 25AUG
                expiry_month = expiry_raw
            return pd.Series([index, expiry_month, strike, option_type])
        else:
            return pd.Series([None, None, None, None])

    all_hist_df[['index', 'expiry_month', 'strike', 'option_type']] = all_hist_df['symbol'].apply(parse_symbol)


    def add_datetime_and_target_columns(df, expiry_date):
        df = df.copy()
        df['date'] = pd.to_datetime(df['date'])
        df['date_only'] = df['date'].dt.date
        df['time'] = df['date'].dt.strftime('%H:%M')
        df['AM_PM'] = df['date'].dt.strftime('%p')
        df['day'] = df['date'].dt.strftime('%A')
        # Assign target_date for each symbol
        def get_target(row):
            delta = (expiry_date.date() - row['date_only']).days
            if delta == 0:
                return 'T'
            elif delta > 0:
                return f'T-{delta}'
            else:
                return f'T+{abs(delta)}'
        df['target_date'] = df.apply(get_target, axis=1)
        return df

    # Example usage:
    all_hist_df = add_datetime_and_target_columns(all_hist_df, expiry_date)
    all_hist_df.sort_values(by=['symbol', 'date'], inplace=True)

    def add_index_open_and_atm_strike(all_hist_df, index_open, atm_strike, start_date, end_date):
        # Add columns for index_open and atm_strike to all rows
        all_hist_df['index_open'] = index_open
        all_hist_df['atm_strike'] = atm_strike
        all_hist_df['start_date'] = start_date
        all_hist_df['end_date'] = end_date
        return all_hist_df

    # Usage example:
    all_hist_df = add_index_open_and_atm_strike(all_hist_df, index_open, atm_strike, start_date, end_date)
    all_hist_df['date'] = pd.to_datetime(all_hist_df['date']).dt.tz_localize(None)

    # ----------------
    # 8. Summary
    # ----------------
    print(f"\nTotal option trading symbols generated: {len(trading_symbols)}")
    print(f"Total mapped tokens found: {len(token_map)}")
    print(f"Historical rows fetched for options: {len(all_hist_df)}")
    print(f"Sample quotes fetched: {len(quotes_df)}")

    return index_open, index_ltp, atm_strike, token_map, all_hist_df, quotes_df

In [18]:
def fetch_index_options_monthly_data(kite, index_symbol, start_date, end_date, expiry_date, interval="day", step=None):
    """
    Fetch index historical data (NIFTY 50 or SENSEX), determine ATM strike,
    generate option trading symbols (CE + PE for all strikes, including ATM),
    map them to instrument tokens, fetch their historical data, and get latest quotes.
    """
    import pandas as pd
    from datetime import datetime, time

    # ----------------
    # INDEX METADATA
    # ----------------
    index_map = {
        "SENSEX": {"token": 265, "exchange": "BSE", "step": 100, "opt_segment": "BFO"},
        "NIFTY 50": {"token": 256265, "exchange": "NSE", "step": 50, "opt_segment": "NFO"}
    }

    if index_symbol.upper() not in [key.upper() for key in index_map.keys()]:
        raise ValueError("Invalid index symbol. Use 'SENSEX' or 'NIFTY 50'")

    # Pick correct config
    for k, v in index_map.items():
        if k.upper() == index_symbol.upper():
            index_cfg = v
            index_symbol_std = k
            break

    if step is None:
        step = index_cfg["step"]

    # ----------------
    # 1. Fetch Index Historical Data
    # ----------------
    hist = kite.historical_data(index_cfg["token"], start_date, start_date, interval="day")
    df_hist = pd.DataFrame(hist)
    df_hist['date'] = pd.to_datetime(df_hist['date'])
    index_open = int(df_hist['open'][0])

    # LTP of index
    full_symbol = f"{index_cfg['exchange']}:{index_symbol_std}"
    index_ltp = kite.quote(full_symbol)[full_symbol]['last_price']

    print("\n---")
    print(f"Current {index_symbol_std} LTP: {index_ltp}")
    print(f"{index_symbol_std} Open on {start_date.date()}: {index_open}")

    # ----------------
    # 2. ATM Calculation
    # ----------------
    atm_strike = int(round(index_open / step) * step)
    print(f"ATM Strike: {atm_strike}")

    # Strike Range
    strike_range = [atm_strike + i * step for i in range(-50, 51)]

    # ----------------
    # 3. Expiry String & Trading Symbols
    # ----------------
    expiry_str_bse = f"{expiry_date.year % 100}{expiry_date.strftime('%b').upper()}"  # e.g., 25AUG
    expiry_str_nse = f"{expiry_date.year % 100}{expiry_date.strftime('%b').upper()}"  # e.g., 25AUG

    trading_symbols = []
    for strike in strike_range:
        if index_cfg['exchange'] == 'BSE':  # SENSEX
            trading_symbols.append(f"{index_symbol_std}{expiry_str_bse}{strike}CE")
            trading_symbols.append(f"{index_symbol_std}{expiry_str_bse}{strike}PE")
        else:  # NSE (NIFTY)
            nse_opts_symbol_prefix = "NIFTY" if "NIFTY" in index_symbol_std.upper() else index_symbol_std.replace(' ', '')
            trading_symbols.append(f"{nse_opts_symbol_prefix}{expiry_str_nse}{strike}CE")
            trading_symbols.append(f"{nse_opts_symbol_prefix}{expiry_str_nse}{strike}PE")

    # ----------------
    # 4. Map to Tokens
    # ----------------
    try:
        instruments_df = pd.DataFrame(kite.instruments(index_cfg["opt_segment"]))
        index_ops = instruments_df[
            (instruments_df['exchange'] == index_cfg["opt_segment"]) &
            (instruments_df['segment'] == f"{index_cfg['opt_segment']}-OPT") &
            (instruments_df['tradingsymbol'].isin(trading_symbols)) &
            (instruments_df['expiry'] == expiry_date.date())
        ]
        
        token_map = {
            row['tradingsymbol']: row['instrument_token']
            for _, row in index_ops.iterrows()
        }
        print("\nMapped Options Tokens:")
        print(token_map)
    except Exception as e:
        print("\nCould not fetch instruments or no options available.")
        print(str(e))
        token_map = {}

    # ----------------
    # 5. Historical Data for Options
    # ----------------
    market_close_time = time(15, 30)
    if start_date.date() == end_date.date():
        if end_date.time() > market_close_time:
            end_date = datetime.combine(end_date.date(), market_close_time)

    all_hist_df = pd.DataFrame()
    for symbol, token in {s: token_map.get(s) for s in trading_symbols}.items():
        if token:
            try:
                hist = kite.historical_data(token, start_date, end_date, interval=interval)
                df_hist = pd.DataFrame(hist)
                df_hist["symbol"] = symbol
                df_hist["token"] = token
                all_hist_df = pd.concat([all_hist_df, df_hist], ignore_index=True)
            except Exception as e:
                print(f"Error fetching data for {symbol}: {e}")
        else:
            print(f"Token not found for {symbol}")

    # Filter candles after market close
    if not all_hist_df.empty:
        all_hist_df['date'] = pd.to_datetime(all_hist_df['date'])
        all_hist_df = all_hist_df[all_hist_df['date'].dt.time <= market_close_time]

    # ----------------
    # 6. Latest Quotes (sample subset)
    # ----------------
    token_map_sample = dict(list(token_map.items())[:5])
    tokens = list(token_map_sample.values())
    if tokens:
        quotes = kite.quote(tokens)
        quotes_df = pd.DataFrame([
            {"symbol": sym, "token": tok, **quotes[str(tok)]}
            for sym, tok in token_map_sample.items()
        ])
    else:
        quotes_df = pd.DataFrame()


    # ----------------
    # 7. Add Index Value (NIFTY/SENSEX) to all option candles
    # ----------------
    try:
        # Fetch intraday index historical data matching 'interval'
        index_hist = kite.historical_data(
            index_cfg["token"],
            start_date,
            end_date,
            interval=interval
        )
        df_index = pd.DataFrame(index_hist)
        df_index['date'] = pd.to_datetime(df_index['date'])
        df_index.rename(columns={'close': f'index_close'}, inplace=True)

        if not all_hist_df.empty:
            # Merge option candles with index value at same timestamp
            all_hist_df = pd.merge(
                all_hist_df,
                df_index[['date', f'index_close']],
                on="date",
                how="left"
            )
            print(f"\nAdded {index_symbol_std} values as a column to options dataframe.")
        else:
            print("\nOptions dataframe empty, skipping index merge.")

    except Exception as e:
        print(f"\nError adding {index_symbol_std} values to options dataframe: {e}")


    def parse_symbol(symbol):
        # Example symbol: NIFTY25AUG24800PE or NIFTY2581424800PE
        match = re.match(r'([A-Z]+)(\d{2}[A-Z]{3}|\d{5})(\d+)(CE|PE)', symbol)
        if match:
            index = match.group(1)
            expiry_raw = match.group(2)
            strike = match.group(3)
            option_type = match.group(4)
            # Format expiry month
            if len(expiry_raw) == 5:  # e.g., 25814
            #     year = "20" + expiry_raw[:2]
            #     month_num = int(expiry_raw[2])
            #     day = expiry_raw[3:]
            #     month = pd.to_datetime(f"{year}-{month_num}-01").strftime("%b").upper()
            #     expiry_month = f"{expiry_raw[:2]}-{month}-{day}"
            # else:  # e.g., 25AUG
                expiry_month = expiry_raw
            return pd.Series([index, expiry_month, strike, option_type])
        else:
            return pd.Series([None, None, None, None])

    all_hist_df[['index', 'expiry_month', 'strike', 'option_type']] = all_hist_df['symbol'].apply(parse_symbol)


    def add_datetime_and_target_columns(df, expiry_date):
        df = df.copy()
        df['date'] = pd.to_datetime(df['date'])
        df['date_only'] = df['date'].dt.date
        df['time'] = df['date'].dt.strftime('%H:%M')
        df['AM_PM'] = df['date'].dt.strftime('%p')
        df['day'] = df['date'].dt.strftime('%A')
        # Assign target_date for each symbol
        def get_target(row):
            delta = (expiry_date.date() - row['date_only']).days
            if delta == 0:
                return 'T'
            elif delta > 0:
                return f'T-{delta}'
            else:
                return f'T+{abs(delta)}'
        df['target_date'] = df.apply(get_target, axis=1)
        return df

    # Example usage:
    all_hist_df = add_datetime_and_target_columns(all_hist_df, expiry_date)
    all_hist_df.sort_values(by=['symbol', 'date'], inplace=True)

    def add_index_open_and_atm_strike(all_hist_df, index_open, atm_strike, start_date, end_date):
        # Add columns for index_open and atm_strike to all rows
        all_hist_df['index_open'] = index_open
        all_hist_df['atm_strike'] = atm_strike
        all_hist_df['start_date'] = start_date
        all_hist_df['end_date'] = end_date
        return all_hist_df

    # Usage example:
    all_hist_df = add_index_open_and_atm_strike(all_hist_df, index_open, atm_strike, start_date, end_date)
    all_hist_df['date'] = pd.to_datetime(all_hist_df['date']).dt.tz_localize(None)


    # ----------------
    # 8. Summary
    # ----------------
    print(f"\nTotal option trading symbols generated: {len(trading_symbols)}")
    print(f"Total mapped tokens found: {len(token_map)}")
    print(f"Historical rows fetched for options: {len(all_hist_df)}")
    print(f"Sample quotes fetched: {len(quotes_df)}")

    return index_open, index_ltp, atm_strike, token_map, all_hist_df, quotes_df

In [32]:
## NIFTY - Weekly - 5min

start = datetime(2025, 9, 23, 9, 15)
end = datetime(2025, 10, 7, 15, 45)
index = "NIFTY 50"
expiry_type = "weekly"
nifty_expiry = datetime(2025, 10, 7)
interval = "5minute"

# For NIFTY
nifty_open, nifty_ltp, nf_atm_strike, nf_token_map, nf_option_hist_df, nf_quotes_df  = fetch_index_options_weekly_data(kite, index, start, end, nifty_expiry,interval)

expiry1_date = nifty_expiry.strftime("%Y%m%d")
with pd.ExcelWriter(f'{index}_{expiry_type}_{interval}_{expiry1_date}.xlsx') as writer:
    nf_option_hist_df.to_excel(writer, sheet_name='option_history', index=False)
    nf_quotes_df.to_excel(writer, sheet_name='quotes', index=False)

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/256265/day?from=2025-09-23+09%3A15%3A00&to=2025-09-23+09%3A15%3A00&interval=day&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /quote?i=NSE%3ANIFTY+50 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/NFO HTTP/1.1" 200 443378

---
Current NIFTY 50 LTP: 25108.3
NIFTY 50 Open on 2025-09-23: 25209
ATM Strike: 25200

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9779458/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443

Mapped Options Tokens:
{'NIFTY25O0725100CE': 9829122, 'NIFTY25O0725100PE': 9829378, 'NIFTY25O0725050CE': 9828610, 'NIFTY25O0725050PE': 9828866, 'NIFTY25O0725150CE': 9829634, 'NIFTY25O0725150PE': 9829890, 'NIFTY25O0725000CE': 9827074, 'NIFTY25O0725000PE': 9827586, 'NIFTY25O0725200CE': 9830146, 'NIFTY25O0725200PE': 9830402, 'NIFTY25O0724950CE': 9826562, 'NIFTY25O0724950PE': 9826818, 'NIFTY25O0725250CE': 9830658, 'NIFTY25O0725250PE': 9830914, 'NIFTY25O0724900CE': 9823746, 'NIFTY25O0724900PE': 9825026, 'NIFTY25O0725300CE': 9831170, 'NIFTY25O0725300PE': 9831426, 'NIFTY25O0724850CE': 9822978, 'NIFTY25O0724850PE': 9823234, 'NIFTY25O0725350CE': 9832194, 'NIFTY25O0725350PE': 9832450, 'NIFTY25O0724800CE': 9822466, 'NIFTY25O0724800PE': 9822722, 'NIFTY25O0725400CE': 9832706, 'NIFTY25O0725400PE': 9832962, 'NIFTY25O0724750CE': 9821954, 'NIFTY25O0724750PE': 9822210, 'NIFTY25O0725450CE': 9833218, 'NIFTY25O0725450PE': 9833474, 'NIFTY25O0725500PE': 9833986, 'NIFTY25O0727150CE': 9863170, 'NIFTY25O0727150PE': 9863426, 'NIFTY25O0727100CE': 9859586, 'NIFTY25O0727100PE': 9861378, 'NIFTY25O0727050CE': 9857794, 'NIFTY25O0727050PE': 9859074, 'NIFTY25O0727000CE': 9857282, 'NIFTY25O0727000PE': 9857538, 'NIFTY25O0726950CE': 9856770, 'NIFTY25O0726950PE': 9857026, 'NIFTY25O0726900CE': 9856258, 'NIFTY25O0726900PE': 9856514, 'NIFTY25O0726850CE': 9855234, 'NIFTY25O0726850PE': 9855490, 'NIFTY25O0726800CE': 9854722, 'NIFTY25O0726800PE': 9854978, 'NIFTY25O0726750CE': 9851650, 'NIFTY25O0726750PE': 9851906, 'NIFTY25O0726700CE': 9851138, 'NIFTY25O0726700PE': 9851394, 'NIFTY25O0726650CE': 9850626, 'NIFTY25O0726650PE': 9850882, 'NIFTY25O0726600CE': 9848834, 'NIFTY25O0726600PE': 9849090, 'NIFTY25O0726550CE': 9848322, 'NIFTY25O0726550PE': 9848578, 'NIFTY25O0726500CE': 9847042, 'NIFTY25O0726500PE': 9847298, 'NIFTY25O0726450CE': 9846530, 'NIFTY25O0726450PE': 9846786, 'NIFTY25O0726400CE': 9846018, 'NIFTY25O0726400PE': 9846274, 'NIFTY25O0726350CE': 9845506, 'NIFTY25O0726350PE': 9845762, 'NIFTY25O0726300CE': 9844994, 'NIFTY25O0726300PE': 9845250, 'NIFTY25O0726250CE': 9844482, 'NIFTY25O0726250PE': 9844738, 'NIFTY25O0726200CE': 9843970, 'NIFTY25O0726200PE': 9844226, 'NIFTY25O0726150CE': 9843458, 'NIFTY25O0726150PE': 9843714, 'NIFTY25O0726100CE': 9842946, 'NIFTY25O0726100PE': 9843202, 'NIFTY25O0726050CE': 9842434, 'NIFTY25O0726050PE': 9842690, 'NIFTY25O0726000CE': 9840898, 'NIFTY25O0726000PE': 9841666, 'NIFTY25O0725950CE': 9840386, 'NIFTY25O0725950PE': 9840642, 'NIFTY25O0725900CE': 9839874, 'NIFTY25O0725900PE': 9840130, 'NIFTY25O0725850CE': 9838850, 'NIFTY25O0725850PE': 9839106, 'NIFTY25O0725800CE': 9838082, 'NIFTY25O0725800PE': 9838338, 'NIFTY25O0725750CE': 9836546, 'NIFTY25O0725750PE': 9837826, 'NIFTY25O0725700CE': 9835778, 'NIFTY25O0725700PE': 9836034, 'NIFTY25O0725650CE': 9835266, 'NIFTY25O0725650PE': 9835522, 'NIFTY25O0725600CE': 9834754, 'NIFTY25O0725600PE': 9835010, 'NIFTY25O0725550CE': 9834242, 'NIFTY25O0725550PE': 9834498, 'NIFTY25O0725500CE': 9833730, 'NIFTY25O0724700CE': 9820418, 'NIFTY25O0724700PE': 9820674, 'NIFTY25O0724650CE': 9819906, 'NIFTY25O0724650PE': 9820162, 'NIFTY25O0724600CE': 9819394, 'NIFTY25O0724600PE': 9819650, 'NIFTY25O0724550CE': 9817858, 'NIFTY25O0724550PE': 9818114, 'NIFTY25O0724500CE': 9816834, 'NIFTY25O0724500PE': 9817090, 'NIFTY25O0724450CE': 9815298, 'NIFTY25O0724450PE': 9815554, 'NIFTY25O0724400CE': 9811202, 'NIFTY25O0724400PE': 9811458, 'NIFTY25O0724350CE': 9810690, 'NIFTY25O0724350PE': 9810946, 'NIFTY25O0724300CE': 9810178, 'NIFTY25O0724300PE': 9810434, 'NIFTY25O0724250CE': 9809666, 'NIFTY25O0724250PE': 9809922, 'NIFTY25O0724200CE': 9807106, 'NIFTY25O0724200PE': 9809410, 'NIFTY25O0724150CE': 9806594, 'NIFTY25O0724150PE': 9806850, 'NIFTY25O0724100CE': 9801474, 'NIFTY25O0724100PE': 9801730, 'NIFTY25O0724050CE': 9800962, 'NIFTY25O0724050PE': 9801218, 'NIFTY25O0724000CE': 9800450, 'NIFTY25O0724000PE': 9800706, 'NIFTY25O0723950CE': 9799938, 'NIFTY25O0723950PE': 9800194, 'NIFTY25O0723900CE': 9799426, 'NIFTY25O0723900PE': 9799682, 'NIFTY25O0723850CE': 9798402, 'NIFTY25O0723850PE': 9798658, 'NIFTY25O0723800CE': 9797890, 'NIFTY25O0723800PE': 9798146, 'NIFTY25O0723750CE': 9796866, 'NIFTY25O0723750PE': 9797122, 'NIFTY25O0723700CE': 9796354, 'NIFTY25O0723700PE': 9796610, 'NIFTY25O0723650CE': 9795842, 'NIFTY25O0723650PE': 9796098, 'NIFTY25O0723600CE': 9794818, 'NIFTY25O0723600PE': 9795074, 'NIFTY25O0723550CE': 9792770, 'NIFTY25O0723550PE': 9793026, 'NIFTY25O0723500CE': 9791234, 'NIFTY25O0723500PE': 9791490, 'NIFTY25O0723450CE': 9790210, 'NIFTY25O0723450PE': 9790466, 'NIFTY25O0723400CE': 9789698, 'NIFTY25O0723400PE': 9789954, 'NIFTY25O0723350CE': 9788674, 'NIFTY25O0723350PE': 9788930, 'NIFTY25O0723300CE': 9788162, 'NIFTY25O0723300PE': 9788418, 'NIFTY25O0723250CE': 9787650, 'NIFTY25O0723250PE': 9787906, 'NIFTY25O0723200CE': 9787138, 'NIFTY25O0723200PE': 9787394, 'NIFTY25O0723150CE': 9785090, 'NIFTY25O0723150PE': 9785346, 'NIFTY25O0723100CE': 9784578, 'NIFTY25O0723100PE': 9784834, 'NIFTY25O0723050CE': 9783042, 'NIFTY25O0723050PE': 9783554, 'NIFTY25O0723000CE': 9782530, 'NIFTY25O0723000PE': 9782786, 'NIFTY25O0722950CE': 9782018, 'NIFTY25O0722950PE': 9782274, 'NIFTY25O0722900CE': 9779970, 'NIFTY25O0722900PE': 9780226, 'NIFTY25O0722850CE': 9779458, 'NIFTY25O0722850PE': 9779714}
Token not found for NIFTY25O0722700CE
Token not found for NIFTY25O0722700PE
Token not found for NIFTY25O0722750CE
Token not found for NIFTY25O0722750PE
Token not found for NIFTY25O0722800CE
Token not found for NIFTY25O0722800PE

DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9779714/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9779970/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9780226/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9782018/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9782274/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9782530/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9782786/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9783042/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9783554/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9784578/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9784834/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9785090/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9785346/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9787138/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9787394/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9787650/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9787906/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9788162/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9788418/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9788674/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9788930/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9789698/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9789954/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9790210/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9790466/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9791234/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9791490/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9792770/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9793026/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9794818/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9795074/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9795842/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9796098/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9796354/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9796610/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9796866/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9797122/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9797890/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9798146/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9798402/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9798658/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9799426/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9799682/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9799938/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9800194/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9800450/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9800706/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9800962/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9801218/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9801474/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9801730/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9806594/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9806850/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9807106/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9809410/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9809666/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9809922/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9810178/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9810434/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9810690/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9810946/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9811202/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9811458/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9815298/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9815554/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9816834/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9817090/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/9817858/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443

Token not found for NIFTY25O0727200CE
Token not found for NIFTY25O0727200PE
Token not found for NIFTY25O0727250CE
Token not found for NIFTY25O0727250PE
Token not found for NIFTY25O0727300CE
Token not found for NIFTY25O0727300PE
Token not found for NIFTY25O0727350CE
Token not found for NIFTY25O0727350PE
Token not found for NIFTY25O0727400CE
Token not found for NIFTY25O0727400PE
Token not found for NIFTY25O0727450CE
Token not found for NIFTY25O0727450PE
Token not found for NIFTY25O0727500CE
Token not found for NIFTY25O0727500PE
Token not found for NIFTY25O0727550CE
Token not found for NIFTY25O0727550PE
Token not found for NIFTY25O0727600CE
Token not found for NIFTY25O0727600PE
Token not found for NIFTY25O0727650CE
Token not found for NIFTY25O0727650PE
Token not found for NIFTY25O0727700CE
Token not found for NIFTY25O0727700PE

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/256265/5minute?from=2025-09-23+09%3A15%3A00&to=2025-10-07+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None

Added NIFTY 50 values as a column to options dataframe.

Total option trading symbols generated: 202
Total mapped tokens found: 174
Historical rows fetched for options: 98764
Sample quotes fetched: 5

In [ ]:
nf_option_hist_df

In [214]:
## NIFTY - Weekly - 15min

start = datetime(2025, 8, 19, 9, 15)
end = datetime(2025, 9, 2, 15, 45)
index = "NIFTY 50"
expiry_type = "weekly"
nifty_expiry = datetime(2025, 9, 2)
interval = "15minute"

# For NIFTY
nifty_open, nifty_ltp, nf_atm_strike, nf_token_map, nf_option_hist_df, nf_quotes_df  = fetch_index_options_weekly_data(kite, index, start, end, nifty_expiry,interval)

expiry1_date = nifty_expiry.strftime("%Y%m%d")
with pd.ExcelWriter(f'{index}_{expiry_type}_{interval}_{expiry1_date}.xlsx') as writer:
    nf_option_hist_df.to_excel(writer, sheet_name='option_history', index=False)
    nf_quotes_df.to_excel(writer, sheet_name='quotes', index=False)

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/256265/day?from=2025-08-19+09%3A15%3A00&to=2025-08-19+09%3A15%3A00&interval=day&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /quote?i=NSE%3ANIFTY+50 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/NFO HTTP/1.1" 200 380417

---
Current NIFTY 50 LTP: 24579.6
NIFTY 50 Open on 2025-08-19: 24891
ATM Strike: 24900

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12495106/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443

Mapped Options Tokens:
{'NIFTY2590224650CE': 12527874, 'NIFTY2590224650PE': 12528130, 'NIFTY2590224600CE': 12527362, 'NIFTY2590224600PE': 12527618, 'NIFTY2590224700CE': 12528386, 'NIFTY2590224700PE': 12528642, 'NIFTY2590224550CE': 12526850, 'NIFTY2590224550PE': 12527106, 'NIFTY2590224750CE': 12528898, 'NIFTY2590224750PE': 12529666, 'NIFTY2590224500CE': 12525826, 'NIFTY2590224500PE': 12526082, 'NIFTY2590224800CE': 12529922, 'NIFTY2590224800PE': 12530178, 'NIFTY2590224450CE': 12525314, 'NIFTY2590224450PE': 12525570, 'NIFTY2590224850CE': 12530434, 'NIFTY2590224850PE': 12530690, 'NIFTY2590224400CE': 12524802, 'NIFTY2590224400PE': 12525058, 'NIFTY2590224900CE': 12530946, 'NIFTY2590224900PE': 12531202, 'NIFTY2590224350CE': 12523266, 'NIFTY2590224350PE': 12524546, 'NIFTY2590224950CE': 12531458, 'NIFTY2590224950PE': 12531714, 'NIFTY2590224300CE': 12522242, 'NIFTY2590224300PE': 12523010, 'NIFTY2590225000CE': 12531970, 'NIFTY2590225000PE': 12532226, 'NIFTY2590225050PE': 12532738, 'NIFTY2590226850CE': 12553986, 'NIFTY2590226850PE': 12554242, 'NIFTY2590226800CE': 12553474, 'NIFTY2590226800PE': 12553730, 'NIFTY2590226750CE': 12552962, 'NIFTY2590226750PE': 12553218, 'NIFTY2590226700CE': 12552450, 'NIFTY2590226700PE': 12552706, 'NIFTY2590226650CE': 12551426, 'NIFTY2590226650PE': 12551682, 'NIFTY2590226600CE': 12550914, 'NIFTY2590226600PE': 12551170, 'NIFTY2590226550CE': 12550402, 'NIFTY2590226550PE': 12550658, 'NIFTY2590226500CE': 12549890, 'NIFTY2590226500PE': 12550146, 'NIFTY2590226450CE': 12549378, 'NIFTY2590226450PE': 12549634, 'NIFTY2590226400CE': 12548866, 'NIFTY2590226400PE': 12549122, 'NIFTY2590226350CE': 12548354, 'NIFTY2590226350PE': 12548610, 'NIFTY2590226300CE': 12547842, 'NIFTY2590226300PE': 12548098, 'NIFTY2590226250CE': 12547330, 'NIFTY2590226250PE': 12547586, 'NIFTY2590226200CE': 12546818, 'NIFTY2590226200PE': 12547074, 'NIFTY2590226150CE': 12546306, 'NIFTY2590226150PE': 12546562, 'NIFTY2590226100CE': 12545794, 'NIFTY2590226100PE': 12546050, 'NIFTY2590226050CE': 12545282, 'NIFTY2590226050PE': 12545538, 'NIFTY2590226000CE': 12544258, 'NIFTY2590226000PE': 12544514, 'NIFTY2590225950CE': 12543746, 'NIFTY2590225950PE': 12544002, 'NIFTY2590225900CE': 12543234, 'NIFTY2590225900PE': 12543490, 'NIFTY2590225850CE': 12542210, 'NIFTY2590225850PE': 12542466, 'NIFTY2590225800CE': 12541698, 'NIFTY2590225800PE': 12541954, 'NIFTY2590225750CE': 12541186, 'NIFTY2590225750PE': 12541442, 'NIFTY2590225700CE': 12540674, 'NIFTY2590225700PE': 12540930, 'NIFTY2590225650CE': 12540162, 'NIFTY2590225650PE': 12540418, 'NIFTY2590225600CE': 12539650, 'NIFTY2590225600PE': 12539906, 'NIFTY2590225550CE': 12539138, 'NIFTY2590225550PE': 12539394, 'NIFTY2590225500CE': 12538626, 'NIFTY2590225500PE': 12538882, 'NIFTY2590225450CE': 12538114, 'NIFTY2590225450PE': 12538370, 'NIFTY2590225400CE': 12537602, 'NIFTY2590225400PE': 12537858, 'NIFTY2590225350CE': 12537090, 'NIFTY2590225350PE': 12537346, 'NIFTY2590225300CE': 12536578, 'NIFTY2590225300PE': 12536834, 'NIFTY2590225250CE': 12535554, 'NIFTY2590225250PE': 12536322, 'NIFTY2590225200CE': 12535042, 'NIFTY2590225200PE': 12535298, 'NIFTY2590225150CE': 12533506, 'NIFTY2590225150PE': 12534786, 'NIFTY2590225100CE': 12532994, 'NIFTY2590225100PE': 12533250, 'NIFTY2590225050CE': 12532482, 'NIFTY2590224250CE': 12520706, 'NIFTY2590224250PE': 12521986, 'NIFTY2590224200CE': 12520194, 'NIFTY2590224200PE': 12520450, 'NIFTY2590224150CE': 12519682, 'NIFTY2590224150PE': 12519938, 'NIFTY2590224100CE': 12518402, 'NIFTY2590224100PE': 12519170, 'NIFTY2590224050CE': 12517122, 'NIFTY2590224050PE': 12518146, 'NIFTY2590224000CE': 12516610, 'NIFTY2590224000PE': 12516866, 'NIFTY2590223950CE': 12514818, 'NIFTY2590223950PE': 12515842, 'NIFTY2590223900CE': 12514050, 'NIFTY2590223900PE': 12514562, 'NIFTY2590223850CE': 12513538, 'NIFTY2590223850PE': 12513794, 'NIFTY2590223800CE': 12512514, 'NIFTY2590223800PE': 12513282, 'NIFTY2590223750CE': 12512002, 'NIFTY2590223750PE': 12512258, 'NIFTY2590223700CE': 12510978, 'NIFTY2590223700PE': 12511234, 'NIFTY2590223650CE': 12510466, 'NIFTY2590223650PE': 12510722, 'NIFTY2590223600CE': 12509954, 'NIFTY2590223600PE': 12510210, 'NIFTY2590223550CE': 12508930, 'NIFTY2590223550PE': 12509698, 'NIFTY2590223500CE': 12508418, 'NIFTY2590223500PE': 12508674, 'NIFTY2590223450CE': 12506882, 'NIFTY2590223450PE': 12507138, 'NIFTY2590223400CE': 12506370, 'NIFTY2590223400PE': 12506626, 'NIFTY2590223350CE': 12505346, 'NIFTY2590223350PE': 12506114, 'NIFTY2590223300CE': 12504834, 'NIFTY2590223300PE': 12505090, 'NIFTY2590223250CE': 12503810, 'NIFTY2590223250PE': 12504578, 'NIFTY2590223200CE': 12503298, 'NIFTY2590223200PE': 12503554, 'NIFTY2590223150CE': 12502274, 'NIFTY2590223150PE': 12502530, 'NIFTY2590223100CE': 12501762, 'NIFTY2590223100PE': 12502018, 'NIFTY2590223050CE': 12501250, 'NIFTY2590223050PE': 12501506, 'NIFTY2590223000CE': 12500738, 'NIFTY2590223000PE': 12500994, 'NIFTY2590222950CE': 12500226, 'NIFTY2590222950PE': 12500482, 'NIFTY2590222900CE': 12499714, 'NIFTY2590222900PE': 12499970, 'NIFTY2590222850CE': 12499202, 'NIFTY2590222850PE': 12499458, 'NIFTY2590222800CE': 12498690, 'NIFTY2590222800PE': 12498946, 'NIFTY2590222750CE': 12498178, 'NIFTY2590222750PE': 12498434, 'NIFTY2590222700CE': 12497666, 'NIFTY2590222700PE': 12497922, 'NIFTY2590222650CE': 12496642, 'NIFTY2590222650PE': 12497410, 'NIFTY2590222600CE': 12495106, 'NIFTY2590222600PE': 12496386}
Token not found for NIFTY2590222400CE
Token not found for NIFTY2590222400PE
Token not found for NIFTY2590222450CE
Token not found for NIFTY2590222450PE
Token not found for NIFTY2590222500CE
Token not found for NIFTY2590222500PE
Token not found for NIFTY2590222550CE
Token not found for NIFTY2590222550PE

DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12496386/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12496642/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12497410/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12497666/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12497922/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12498178/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12498434/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12498690/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12498946/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12499202/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12499458/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12499714/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12499970/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12500226/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12500482/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12500738/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12500994/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12501250/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12501506/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12501762/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12502018/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12502274/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12502530/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12503298/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12503554/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12503810/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12504578/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12504834/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12505090/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12505346/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12506114/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12506370/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12506626/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12506882/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12507138/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12508418/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12508674/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12508930/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12509698/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12509954/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12510210/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12510466/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12510722/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12510978/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12511234/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12512002/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12512258/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12512514/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12513282/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12513538/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12513794/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12514050/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12514562/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12514818/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12515842/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12516610/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12516866/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12517122/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12518146/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12518402/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12519170/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12519682/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12519938/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12520194/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12520450/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12520706/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/12521986/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443

Token not found for NIFTY2590226900CE
Token not found for NIFTY2590226900PE
Token not found for NIFTY2590226950CE
Token not found for NIFTY2590226950PE
Token not found for NIFTY2590227000CE
Token not found for NIFTY2590227000PE
Token not found for NIFTY2590227050CE
Token not found for NIFTY2590227050PE
Token not found for NIFTY2590227100CE
Token not found for NIFTY2590227100PE
Token not found for NIFTY2590227150CE
Token not found for NIFTY2590227150PE
Token not found for NIFTY2590227200CE
Token not found for NIFTY2590227200PE
Token not found for NIFTY2590227250CE
Token not found for NIFTY2590227250PE
Token not found for NIFTY2590227300CE
Token not found for NIFTY2590227300PE
Token not found for NIFTY2590227350CE
Token not found for NIFTY2590227350PE
Token not found for NIFTY2590227400CE
Token not found for NIFTY2590227400PE

DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /quote?i=12527874&i=12528130&i=12527362&i=12527618&i=12528386 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/256265/15minute?from=2025-08-19+09%3A15%3A00&to=2025-09-02+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None

Added NIFTY 50 values as a column to options dataframe.

Total option trading symbols generated: 202
Total mapped tokens found: 172
Historical rows fetched for options: 32062
Sample quotes fetched: 5

In [19]:
## NIFTY - Monthly - 5min

start = datetime(2025, 9, 16, 9, 15)
end = datetime(2025, 9, 30, 15, 45)
index = "NIFTY 50"
expiry_type = "monthly"
expiry_date = datetime(2025, 9, 30)
interval = "5minute"

# For NIFTY
nifty_open, nifty_ltp, nf_atm_strike, nf_token_map, nf_option_hist_df, nf_quotes_df  = fetch_index_options_monthly_data(kite, index, start, end, nifty_expiry,interval)

expiry1_date = expiry_date.strftime("%Y%m%d")
with pd.ExcelWriter(f'{index}_{expiry_type}_{interval}_{expiry1_date}.xlsx') as writer:
    nf_option_hist_df.to_excel(writer, sheet_name='option_history', index=False)
    nf_quotes_df.to_excel(writer, sheet_name='quotes', index=False)

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/256265/day?from=2025-09-16+09%3A15%3A00&to=2025-09-16+09%3A15%3A00&interval=day&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /quote?i=NSE%3ANIFTY+50 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/NFO HTTP/1.1" 200 451500

---
Current NIFTY 50 LTP: 24611.1
NIFTY 50 Open on 2025-09-16: 25073
ATM Strike: 25050

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443

Mapped Options Tokens:
{'NIFTY25SEP24650CE': 15476482, 'NIFTY25SEP24650PE': 15476738, 'NIFTY25SEP24600CE': 15475970, 'NIFTY25SEP24600PE': 15476226, 'NIFTY25SEP24700CE': 15476994, 'NIFTY25SEP24700PE': 15477762, 'NIFTY25SEP24550CE': 15475458, 'NIFTY25SEP24550PE': 15475714, 'NIFTY25SEP24750CE': 15478018, 'NIFTY25SEP24750PE': 15478786, 'NIFTY25SEP24500CE': 15473410, 'NIFTY25SEP24500PE': 15475202, 'NIFTY25SEP24800CE': 15479042, 'NIFTY25SEP24800PE': 15479298, 'NIFTY25SEP24450CE': 15472898, 'NIFTY25SEP24450PE': 15473154, 'NIFTY25SEP24850CE': 15479554, 'NIFTY25SEP24850PE': 15479810, 'NIFTY25SEP24400CE': 15469314, 'NIFTY25SEP24400PE': 15472642, 'NIFTY25SEP24900CE': 15480066, 'NIFTY25SEP24900PE': 15480322, 'NIFTY25SEP24350CE': 15462914, 'NIFTY25SEP24350PE': 15463938, 'NIFTY25SEP24950CE': 15481346, 'NIFTY25SEP24950PE': 15481602, 'NIFTY25SEP24300CE': 15461890, 'NIFTY25SEP24300PE': 15462658, 'NIFTY25SEP25000CE': 16561666, 'NIFTY25SEP25000PE': 16561922, 'NIFTY25SEP25050PE': 15483394, 'NIFTY25SEP27400CE': 15520002, 'NIFTY25SEP27400PE': 15520258, 'NIFTY25SEP27350CE': 15519490, 'NIFTY25SEP27350PE': 15519746, 'NIFTY25SEP27300CE': 15518978, 'NIFTY25SEP27300PE': 15519234, 'NIFTY25SEP27250CE': 15518466, 'NIFTY25SEP27250PE': 15518722, 'NIFTY25SEP27200CE': 15517442, 'NIFTY25SEP27200PE': 15518210, 'NIFTY25SEP27150CE': 15516930, 'NIFTY25SEP27150PE': 15517186, 'NIFTY25SEP27100CE': 15516418, 'NIFTY25SEP27100PE': 15516674, 'NIFTY25SEP27050CE': 15515906, 'NIFTY25SEP27050PE': 15516162, 'NIFTY25SEP27000CE': 16562690, 'NIFTY25SEP27000PE': 16562946, 'NIFTY25SEP26950CE': 15515394, 'NIFTY25SEP26950PE': 15515650, 'NIFTY25SEP26900CE': 15514882, 'NIFTY25SEP26900PE': 15515138, 'NIFTY25SEP26850CE': 15514370, 'NIFTY25SEP26850PE': 15514626, 'NIFTY25SEP26800CE': 15513858, 'NIFTY25SEP26800PE': 15514114, 'NIFTY25SEP26750CE': 15513346, 'NIFTY25SEP26750PE': 15513602, 'NIFTY25SEP26700CE': 15512834, 'NIFTY25SEP26700PE': 15513090, 'NIFTY25SEP26650CE': 15512322, 'NIFTY25SEP26650PE': 15512578, 'NIFTY25SEP26600CE': 15511810, 'NIFTY25SEP26600PE': 15512066, 'NIFTY25SEP26550CE': 15511298, 'NIFTY25SEP26550PE': 15511554, 'NIFTY25SEP26500CE': 15510786, 'NIFTY25SEP26500PE': 15511042, 'NIFTY25SEP26450CE': 15510274, 'NIFTY25SEP26450PE': 15510530, 'NIFTY25SEP26400CE': 15509762, 'NIFTY25SEP26400PE': 15510018, 'NIFTY25SEP26350CE': 15509250, 'NIFTY25SEP26350PE': 15509506, 'NIFTY25SEP26300CE': 15507458, 'NIFTY25SEP26300PE': 15508994, 'NIFTY25SEP26250CE': 15506946, 'NIFTY25SEP26250PE': 15507202, 'NIFTY25SEP26200CE': 15504898, 'NIFTY25SEP26200PE': 15506690, 'NIFTY25SEP26150CE': 15501826, 'NIFTY25SEP26150PE': 15504642, 'NIFTY25SEP26100CE': 15501314, 'NIFTY25SEP26100PE': 15501570, 'NIFTY25SEP26050CE': 15500290, 'NIFTY25SEP26050PE': 15501058, 'NIFTY25SEP26000CE': 16562178, 'NIFTY25SEP26000PE': 16562434, 'NIFTY25SEP25950CE': 15492610, 'NIFTY25SEP25950PE': 15500034, 'NIFTY25SEP25900CE': 15492098, 'NIFTY25SEP25900PE': 15492354, 'NIFTY25SEP25850CE': 15491586, 'NIFTY25SEP25850PE': 15491842, 'NIFTY25SEP25800CE': 15491074, 'NIFTY25SEP25800PE': 15491330, 'NIFTY25SEP25750CE': 15490562, 'NIFTY25SEP25750PE': 15490818, 'NIFTY25SEP25700CE': 15490050, 'NIFTY25SEP25700PE': 15490306, 'NIFTY25SEP25650CE': 15489282, 'NIFTY25SEP25650PE': 15489538, 'NIFTY25SEP25600CE': 15488770, 'NIFTY25SEP25600PE': 15489026, 'NIFTY25SEP25550CE': 15488258, 'NIFTY25SEP25550PE': 15488514, 'NIFTY25SEP25500CE': 15487746, 'NIFTY25SEP25500PE': 15488002, 'NIFTY25SEP25450CE': 15487234, 'NIFTY25SEP25450PE': 15487490, 'NIFTY25SEP25400CE': 15486722, 'NIFTY25SEP25400PE': 15486978, 'NIFTY25SEP25350CE': 15486210, 'NIFTY25SEP25350PE': 15486466, 'NIFTY25SEP25300CE': 15485698, 'NIFTY25SEP25300PE': 15485954, 'NIFTY25SEP25250CE': 15485186, 'NIFTY25SEP25250PE': 15485442, 'NIFTY25SEP25200CE': 15484674, 'NIFTY25SEP25200PE': 15484930, 'NIFTY25SEP25150CE': 15484162, 'NIFTY25SEP25150PE': 15484418, 'NIFTY25SEP25100CE': 15483650, 'NIFTY25SEP25100PE': 15483906, 'NIFTY25SEP25050CE': 15483138, 'NIFTY25SEP24250CE': 15460098, 'NIFTY25SEP24250PE': 15460354, 'NIFTY25SEP24200CE': 15458306, 'NIFTY25SEP24200PE': 15459842, 'NIFTY25SEP24150CE': 15457794, 'NIFTY25SEP24150PE': 15458050, 'NIFTY25SEP24100CE': 15456514, 'NIFTY25SEP24100PE': 15457538, 'NIFTY25SEP24050CE': 15455490, 'NIFTY25SEP24050PE': 15455746, 'NIFTY25SEP24000CE': 16561154, 'NIFTY25SEP24000PE': 16561410, 'NIFTY25SEP23950CE': 15452930, 'NIFTY25SEP23950PE': 15455234, 'NIFTY25SEP23900CE': 15451906, 'NIFTY25SEP23900PE': 15452674, 'NIFTY25SEP23850CE': 15451394, 'NIFTY25SEP23850PE': 15451650, 'NIFTY25SEP23800CE': 15450370, 'NIFTY25SEP23800PE': 15451138, 'NIFTY25SEP23750CE': 15449602, 'NIFTY25SEP23750PE': 15449858, 'NIFTY25SEP23700CE': 15448834, 'NIFTY25SEP23700PE': 15449090, 'NIFTY25SEP23650CE': 15448322, 'NIFTY25SEP23650PE': 15448578, 'NIFTY25SEP23600CE': 15447298, 'NIFTY25SEP23600PE': 15447554, 'NIFTY25SEP23550CE': 15446786, 'NIFTY25SEP23550PE': 15447042, 'NIFTY25SEP23500CE': 15446274, 'NIFTY25SEP23500PE': 15446530, 'NIFTY25SEP23450CE': 15445762, 'NIFTY25SEP23450PE': 15446018, 'NIFTY25SEP23400CE': 15445250, 'NIFTY25SEP23400PE': 15445506, 'NIFTY25SEP23350CE': 15444738, 'NIFTY25SEP23350PE': 15444994, 'NIFTY25SEP23300CE': 15443714, 'NIFTY25SEP23300PE': 15443970, 'NIFTY25SEP23250CE': 15443202, 'NIFTY25SEP23250PE': 15443458, 'NIFTY25SEP23200CE': 15442690, 'NIFTY25SEP23200PE': 15442946, 'NIFTY25SEP23150CE': 15442178, 'NIFTY25SEP23150PE': 15442434, 'NIFTY25SEP23100CE': 15441666, 'NIFTY25SEP23100PE': 15441922, 'NIFTY25SEP23050CE': 15441154, 'NIFTY25SEP23050PE': 15441410, 'NIFTY25SEP23000CE': 16560642, 'NIFTY25SEP23000PE': 16560898, 'NIFTY25SEP22950CE': 15440642, 'NIFTY25SEP22950PE': 15440898, 'NIFTY25SEP22900CE': 15440130, 'NIFTY25SEP22900PE': 15440386, 'NIFTY25SEP22850CE': 15439618, 'NIFTY25SEP22850PE': 15439874, 'NIFTY25SEP22800CE': 15439106, 'NIFTY25SEP22800PE': 15439362, 'NIFTY25SEP22750CE': 15438594, 'NIFTY25SEP22750PE': 15438850, 'NIFTY25SEP22700CE': 15438082, 'NIFTY25SEP22700PE': 15438338, 'NIFTY25SEP22650CE': 15437570, 'NIFTY25SEP22650PE': 15437826, 'NIFTY25SEP22600CE': 15437058, 'NIFTY25SEP22600PE': 15437314}
Token not found for NIFTY25SEP22550CE
Token not found for NIFTY25SEP22550PE

DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15437058/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15437314/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15437570/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15437826/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15438082/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15438338/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15438594/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15438850/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15439106/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15439362/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15439618/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15439874/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15440130/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15440386/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15440642/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15440898/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/16560642/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/16560898/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15441154/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15441410/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15441666/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15441922/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15442178/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15442434/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15442690/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15442946/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15443202/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15443458/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15443714/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15443970/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15444738/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15444994/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15445250/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15445506/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15445762/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15446018/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15446274/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15446530/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15446786/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15447042/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15447298/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15447554/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15448322/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15448578/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15448834/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15449090/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15449602/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15449858/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15450370/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15451138/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15451394/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15451650/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15451906/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15452674/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15452930/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15455234/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/16561154/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/16561410/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15455490/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15455746/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15456514/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15457538/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15457794/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15458050/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15458306/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15459842/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15460098/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15460354/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None

Token not found for NIFTY25SEP27450CE
Token not found for NIFTY25SEP27450PE
Token not found for NIFTY25SEP27500CE
Token not found for NIFTY25SEP27500PE
Token not found for NIFTY25SEP27550CE
Token not found for NIFTY25SEP27550PE

DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/256265/5minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None

Added NIFTY 50 values as a column to options dataframe.

Total option trading symbols generated: 202
Total mapped tokens found: 194
Historical rows fetched for options: 131141
Sample quotes fetched: 5

In [20]:
## NIFTY - Monthly - 15min

start = datetime(2025, 9, 16, 9, 15)
end = datetime(2025, 9, 30, 15, 45)
index = "NIFTY 50"
expiry_type = "monthly"
expiry_date = datetime(2025, 9, 30)
interval = "15minute"

# For NIFTY
nifty_open, nifty_ltp, nf_atm_strike, nf_token_map, nf_option_hist_df, nf_quotes_df  = fetch_index_options_monthly_data(kite, index, start, end, nifty_expiry,interval)

expiry1_date = expiry_date.strftime("%Y%m%d")
with pd.ExcelWriter(f'{index}_{expiry_type}_{interval}_{expiry1_date}.xlsx') as writer:
    nf_option_hist_df.to_excel(writer, sheet_name='option_history', index=False)
    nf_quotes_df.to_excel(writer, sheet_name='quotes', index=False)

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/256265/day?from=2025-09-16+09%3A15%3A00&to=2025-09-16+09%3A15%3A00&interval=day&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /quote?i=NSE%3ANIFTY+50 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/NFO HTTP/1.1" 200 451500

---
Current NIFTY 50 LTP: 24611.1
NIFTY 50 Open on 2025-09-16: 25073
ATM Strike: 25050

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15437058/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443

Mapped Options Tokens:
{'NIFTY25SEP24650CE': 15476482, 'NIFTY25SEP24650PE': 15476738, 'NIFTY25SEP24600CE': 15475970, 'NIFTY25SEP24600PE': 15476226, 'NIFTY25SEP24700CE': 15476994, 'NIFTY25SEP24700PE': 15477762, 'NIFTY25SEP24550CE': 15475458, 'NIFTY25SEP24550PE': 15475714, 'NIFTY25SEP24750CE': 15478018, 'NIFTY25SEP24750PE': 15478786, 'NIFTY25SEP24500CE': 15473410, 'NIFTY25SEP24500PE': 15475202, 'NIFTY25SEP24800CE': 15479042, 'NIFTY25SEP24800PE': 15479298, 'NIFTY25SEP24450CE': 15472898, 'NIFTY25SEP24450PE': 15473154, 'NIFTY25SEP24850CE': 15479554, 'NIFTY25SEP24850PE': 15479810, 'NIFTY25SEP24400CE': 15469314, 'NIFTY25SEP24400PE': 15472642, 'NIFTY25SEP24900CE': 15480066, 'NIFTY25SEP24900PE': 15480322, 'NIFTY25SEP24350CE': 15462914, 'NIFTY25SEP24350PE': 15463938, 'NIFTY25SEP24950CE': 15481346, 'NIFTY25SEP24950PE': 15481602, 'NIFTY25SEP24300CE': 15461890, 'NIFTY25SEP24300PE': 15462658, 'NIFTY25SEP25000CE': 16561666, 'NIFTY25SEP25000PE': 16561922, 'NIFTY25SEP25050PE': 15483394, 'NIFTY25SEP27400CE': 15520002, 'NIFTY25SEP27400PE': 15520258, 'NIFTY25SEP27350CE': 15519490, 'NIFTY25SEP27350PE': 15519746, 'NIFTY25SEP27300CE': 15518978, 'NIFTY25SEP27300PE': 15519234, 'NIFTY25SEP27250CE': 15518466, 'NIFTY25SEP27250PE': 15518722, 'NIFTY25SEP27200CE': 15517442, 'NIFTY25SEP27200PE': 15518210, 'NIFTY25SEP27150CE': 15516930, 'NIFTY25SEP27150PE': 15517186, 'NIFTY25SEP27100CE': 15516418, 'NIFTY25SEP27100PE': 15516674, 'NIFTY25SEP27050CE': 15515906, 'NIFTY25SEP27050PE': 15516162, 'NIFTY25SEP27000CE': 16562690, 'NIFTY25SEP27000PE': 16562946, 'NIFTY25SEP26950CE': 15515394, 'NIFTY25SEP26950PE': 15515650, 'NIFTY25SEP26900CE': 15514882, 'NIFTY25SEP26900PE': 15515138, 'NIFTY25SEP26850CE': 15514370, 'NIFTY25SEP26850PE': 15514626, 'NIFTY25SEP26800CE': 15513858, 'NIFTY25SEP26800PE': 15514114, 'NIFTY25SEP26750CE': 15513346, 'NIFTY25SEP26750PE': 15513602, 'NIFTY25SEP26700CE': 15512834, 'NIFTY25SEP26700PE': 15513090, 'NIFTY25SEP26650CE': 15512322, 'NIFTY25SEP26650PE': 15512578, 'NIFTY25SEP26600CE': 15511810, 'NIFTY25SEP26600PE': 15512066, 'NIFTY25SEP26550CE': 15511298, 'NIFTY25SEP26550PE': 15511554, 'NIFTY25SEP26500CE': 15510786, 'NIFTY25SEP26500PE': 15511042, 'NIFTY25SEP26450CE': 15510274, 'NIFTY25SEP26450PE': 15510530, 'NIFTY25SEP26400CE': 15509762, 'NIFTY25SEP26400PE': 15510018, 'NIFTY25SEP26350CE': 15509250, 'NIFTY25SEP26350PE': 15509506, 'NIFTY25SEP26300CE': 15507458, 'NIFTY25SEP26300PE': 15508994, 'NIFTY25SEP26250CE': 15506946, 'NIFTY25SEP26250PE': 15507202, 'NIFTY25SEP26200CE': 15504898, 'NIFTY25SEP26200PE': 15506690, 'NIFTY25SEP26150CE': 15501826, 'NIFTY25SEP26150PE': 15504642, 'NIFTY25SEP26100CE': 15501314, 'NIFTY25SEP26100PE': 15501570, 'NIFTY25SEP26050CE': 15500290, 'NIFTY25SEP26050PE': 15501058, 'NIFTY25SEP26000CE': 16562178, 'NIFTY25SEP26000PE': 16562434, 'NIFTY25SEP25950CE': 15492610, 'NIFTY25SEP25950PE': 15500034, 'NIFTY25SEP25900CE': 15492098, 'NIFTY25SEP25900PE': 15492354, 'NIFTY25SEP25850CE': 15491586, 'NIFTY25SEP25850PE': 15491842, 'NIFTY25SEP25800CE': 15491074, 'NIFTY25SEP25800PE': 15491330, 'NIFTY25SEP25750CE': 15490562, 'NIFTY25SEP25750PE': 15490818, 'NIFTY25SEP25700CE': 15490050, 'NIFTY25SEP25700PE': 15490306, 'NIFTY25SEP25650CE': 15489282, 'NIFTY25SEP25650PE': 15489538, 'NIFTY25SEP25600CE': 15488770, 'NIFTY25SEP25600PE': 15489026, 'NIFTY25SEP25550CE': 15488258, 'NIFTY25SEP25550PE': 15488514, 'NIFTY25SEP25500CE': 15487746, 'NIFTY25SEP25500PE': 15488002, 'NIFTY25SEP25450CE': 15487234, 'NIFTY25SEP25450PE': 15487490, 'NIFTY25SEP25400CE': 15486722, 'NIFTY25SEP25400PE': 15486978, 'NIFTY25SEP25350CE': 15486210, 'NIFTY25SEP25350PE': 15486466, 'NIFTY25SEP25300CE': 15485698, 'NIFTY25SEP25300PE': 15485954, 'NIFTY25SEP25250CE': 15485186, 'NIFTY25SEP25250PE': 15485442, 'NIFTY25SEP25200CE': 15484674, 'NIFTY25SEP25200PE': 15484930, 'NIFTY25SEP25150CE': 15484162, 'NIFTY25SEP25150PE': 15484418, 'NIFTY25SEP25100CE': 15483650, 'NIFTY25SEP25100PE': 15483906, 'NIFTY25SEP25050CE': 15483138, 'NIFTY25SEP24250CE': 15460098, 'NIFTY25SEP24250PE': 15460354, 'NIFTY25SEP24200CE': 15458306, 'NIFTY25SEP24200PE': 15459842, 'NIFTY25SEP24150CE': 15457794, 'NIFTY25SEP24150PE': 15458050, 'NIFTY25SEP24100CE': 15456514, 'NIFTY25SEP24100PE': 15457538, 'NIFTY25SEP24050CE': 15455490, 'NIFTY25SEP24050PE': 15455746, 'NIFTY25SEP24000CE': 16561154, 'NIFTY25SEP24000PE': 16561410, 'NIFTY25SEP23950CE': 15452930, 'NIFTY25SEP23950PE': 15455234, 'NIFTY25SEP23900CE': 15451906, 'NIFTY25SEP23900PE': 15452674, 'NIFTY25SEP23850CE': 15451394, 'NIFTY25SEP23850PE': 15451650, 'NIFTY25SEP23800CE': 15450370, 'NIFTY25SEP23800PE': 15451138, 'NIFTY25SEP23750CE': 15449602, 'NIFTY25SEP23750PE': 15449858, 'NIFTY25SEP23700CE': 15448834, 'NIFTY25SEP23700PE': 15449090, 'NIFTY25SEP23650CE': 15448322, 'NIFTY25SEP23650PE': 15448578, 'NIFTY25SEP23600CE': 15447298, 'NIFTY25SEP23600PE': 15447554, 'NIFTY25SEP23550CE': 15446786, 'NIFTY25SEP23550PE': 15447042, 'NIFTY25SEP23500CE': 15446274, 'NIFTY25SEP23500PE': 15446530, 'NIFTY25SEP23450CE': 15445762, 'NIFTY25SEP23450PE': 15446018, 'NIFTY25SEP23400CE': 15445250, 'NIFTY25SEP23400PE': 15445506, 'NIFTY25SEP23350CE': 15444738, 'NIFTY25SEP23350PE': 15444994, 'NIFTY25SEP23300CE': 15443714, 'NIFTY25SEP23300PE': 15443970, 'NIFTY25SEP23250CE': 15443202, 'NIFTY25SEP23250PE': 15443458, 'NIFTY25SEP23200CE': 15442690, 'NIFTY25SEP23200PE': 15442946, 'NIFTY25SEP23150CE': 15442178, 'NIFTY25SEP23150PE': 15442434, 'NIFTY25SEP23100CE': 15441666, 'NIFTY25SEP23100PE': 15441922, 'NIFTY25SEP23050CE': 15441154, 'NIFTY25SEP23050PE': 15441410, 'NIFTY25SEP23000CE': 16560642, 'NIFTY25SEP23000PE': 16560898, 'NIFTY25SEP22950CE': 15440642, 'NIFTY25SEP22950PE': 15440898, 'NIFTY25SEP22900CE': 15440130, 'NIFTY25SEP22900PE': 15440386, 'NIFTY25SEP22850CE': 15439618, 'NIFTY25SEP22850PE': 15439874, 'NIFTY25SEP22800CE': 15439106, 'NIFTY25SEP22800PE': 15439362, 'NIFTY25SEP22750CE': 15438594, 'NIFTY25SEP22750PE': 15438850, 'NIFTY25SEP22700CE': 15438082, 'NIFTY25SEP22700PE': 15438338, 'NIFTY25SEP22650CE': 15437570, 'NIFTY25SEP22650PE': 15437826, 'NIFTY25SEP22600CE': 15437058, 'NIFTY25SEP22600PE': 15437314}
Token not found for NIFTY25SEP22550CE
Token not found for NIFTY25SEP22550PE

DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15437314/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15437570/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15437826/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15438082/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15438338/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15438594/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15438850/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15439106/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15439362/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15439618/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15439874/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15440130/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15440386/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15440642/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15440898/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/16560642/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/16560898/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15441154/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15441410/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15441666/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15441922/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15442178/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15442434/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15442690/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15442946/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15443202/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15443458/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15443714/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15443970/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15444738/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15444994/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15445250/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15445506/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15445762/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15446018/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15446274/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15446530/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15446786/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15447042/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15447298/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15447554/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15448322/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15448578/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15448834/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15449090/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15449602/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15449858/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15450370/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15451138/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15451394/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15451650/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15451906/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15452674/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15452930/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15455234/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/16561154/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/16561410/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15455490/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15455746/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15456514/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15457538/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15457794/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15458050/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15458306/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15459842/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15460098/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/15460354/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443

Token not found for NIFTY25SEP27450CE
Token not found for NIFTY25SEP27450PE
Token not found for NIFTY25SEP27500CE
Token not found for NIFTY25SEP27500PE
Token not found for NIFTY25SEP27550CE
Token not found for NIFTY25SEP27550PE

DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/256265/15minute?from=2025-09-16+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None

Added NIFTY 50 values as a column to options dataframe.

Total option trading symbols generated: 202
Total mapped tokens found: 194
Historical rows fetched for options: 44001
Sample quotes fetched: 5

In [ ]:
## NIFTY - Weekly - 5min

start = datetime(2025, 8, 22, 9, 15)
end = datetime(2025, 8, 28, 15, 45)
index = "NIFTY 50"
expiry_type = "weekly"
nifty_expiry = datetime(2025, 8, 28)
interval = "5minute"

# For NIFTY
nifty_open, nifty_ltp, nf_atm_strike, nf_token_map, nf_option_hist_df, nf_quotes_df  = fetch_index_options_monthly_data(kite, index, start, end, nifty_expiry,interval)

expiry1_date = expiry_date.strftime("%Y%m%d")
with pd.ExcelWriter(f'{index}_{expiry_type}_{interval}_{expiry1_date}.xlsx') as writer:
    nf_option_hist_df.to_excel(writer, sheet_name='option_history', index=False)
    nf_quotes_df.to_excel(writer, sheet_name='quotes', index=False)

In [ ]:
## NIFTY - Weekly - 15min

start = datetime(2025, 8, 22, 9, 15)
end = datetime(2025, 8, 28, 15, 45)
index = "NIFTY 50"
expiry_type = "weekly"
nifty_expiry = datetime(2025, 8, 28)
interval = "15minute"

# For NIFTY
nifty_open, nifty_ltp, nf_atm_strike, nf_token_map, nf_option_hist_df, nf_quotes_df  = fetch_index_options_monthly_data(kite, index, start, end, nifty_expiry,interval)

expiry1_date = expiry_date.strftime("%Y%m%d")
with pd.ExcelWriter(f'{index}_{expiry_type}_{interval}_{expiry1_date}.xlsx') as writer:
    nf_option_hist_df.to_excel(writer, sheet_name='option_history', index=False)
    nf_quotes_df.to_excel(writer, sheet_name='quotes', index=False)

In [ ]:
## NIFTY - Weekly Expiry

start = datetime(2025, 8, 22, 9, 15)
end = datetime(2025, 8, 28, 15, 30)

nifty_expiry = datetime(2025, 8, 28)

# For NIFTY
nifty_open, nifty_ltp, nf_atm_strike, nf_token_map, nf_option_hist_df, nf_quotes_df  = fetch_index_options_weekly_data(kite, "NIFTY 50", start, end, nifty_expiry,interval="day")

nf_option_hist_df['date'] = pd.to_datetime(nf_option_hist_df['date']).dt.tz_localize(None)
nf_option_hist_df.to_excel('nifty_options_data_15mM258.xlsx', index=False)

### SENSEX

In [39]:
## SENSEX - Weekly - 5min

start = datetime(2025, 9, 25, 9, 15)
end = datetime(2025, 10, 9, 15, 45)
index = "SENSEX"
expiry_type = "weekly"
expiry = datetime(2025, 10, 9)
interval = "15minute"

# For SENSEX
open, ltp, atm_strike, token_map, option_hist_df, quotes_df  = fetch_index_options_weekly_data(kite, index, start, end, expiry,interval)

expiry1_date = expiry.strftime("%Y%m%d")
with pd.ExcelWriter(f'{index}_{expiry_type}_{interval}_{expiry1_date}.xlsx') as writer:
    option_hist_df.to_excel(writer, sheet_name='option_history', index=False)
    quotes_df.to_excel(writer, sheet_name='quotes', index=False)

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/265/day?from=2025-09-25+09%3A15%3A00&to=2025-09-25+09%3A15%3A00&interval=day&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /quote?i=BSE%3ASENSEX HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/BFO HTTP/1.1" 200 68393

---
Current SENSEX LTP: 82172.1
SENSEX Open on 2025-09-25: 81574
ATM Strike: 81600

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223558405/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443

Mapped Options Tokens:
{'SENSEX25O0981800CE': 223499269, 'SENSEX25O0981800PE': 223544837, 'SENSEX25O0981700PE': 223558661, 'SENSEX25O0981700CE': 223563269, 'SENSEX25O0981900PE': 223485957, 'SENSEX25O0981900CE': 223527429, 'SENSEX25O0981600CE': 223481861, 'SENSEX25O0981600PE': 223525637, 'SENSEX25O0982000PE': 223495429, 'SENSEX25O0982000CE': 223500037, 'SENSEX25O0981500PE': 223497221, 'SENSEX25O0981500CE': 223540485, 'SENSEX25O0982100PE': 223486981, 'SENSEX25O0982100CE': 223528709, 'SENSEX25O0981400PE': 223508997, 'SENSEX25O0981400CE': 223553797, 'SENSEX25O0982200PE': 223514629, 'SENSEX25O0982200CE': 223561477, 'SENSEX25O0981300PE': 223480069, 'SENSEX25O0981300CE': 223523077, 'SENSEX25O0982300PE': 223503365, 'SENSEX25O0982300CE': 223547909, 'SENSEX25O0981200PE': 223491589, 'SENSEX25O0981200CE': 223494149, 'SENSEX25O0982400CE': 223488773, 'SENSEX25O0982400PE': 223531525, 'SENSEX25O0981100CE': 223505669, 'SENSEX25O0981100PE': 223551493, 'SENSEX25O0982500CE': 223475717, 'SENSEX25O0982500PE': 223565829, 'SENSEX25O0982600PE': 223550981, 'SENSEX25O0986600PE': 223507461, 'SENSEX25O0986600CE': 223551749, 'SENSEX25O0986500PE': 223478789, 'SENSEX25O0986500CE': 223521541, 'SENSEX25O0986400PE': 223490309, 'SENSEX25O0986400CE': 223532293, 'SENSEX25O0986300CE': 223503877, 'SENSEX25O0986300PE': 223549957, 'SENSEX25O0986200PE': 223564037, 'SENSEX25O0986200CE': 223568645, 'SENSEX25O0986100CE': 223487493, 'SENSEX25O0986100PE': 223530245, 'SENSEX25O0986000PE': 223501829, 'SENSEX25O0986000CE': 223546373, 'SENSEX25O0985900PE': 223491845, 'SENSEX25O0985900CE': 223533829, 'SENSEX25O0985800PE': 223501061, 'SENSEX25O0985800CE': 223545605, 'SENSEX25O0985700CE': 223516165, 'SENSEX25O0985700PE': 223566085, 'SENSEX25O0985600PE': 223484165, 'SENSEX25O0985600CE': 223526405, 'SENSEX25O0985500CE': 223498245, 'SENSEX25O0985500PE': 223542789, 'SENSEX25O0985400PE': 223556869, 'SENSEX25O0985400CE': 223561989, 'SENSEX25O0985300CE': 223480581, 'SENSEX25O0985300PE': 223524613, 'SENSEX25O0985200PE': 223495941, 'SENSEX25O0985200CE': 223539205, 'SENSEX25O0985100PE': 223507717, 'SENSEX25O0985100CE': 223552005, 'SENSEX25O0985000PE': 223479045, 'SENSEX25O0985000CE': 223521797, 'SENSEX25O0984900CE': 223510277, 'SENSEX25O0984900PE': 223559173, 'SENSEX25O0984800PE': 223477509, 'SENSEX25O0984800CE': 223520773, 'SENSEX25O0984700CE': 223492869, 'SENSEX25O0984700PE': 223537157, 'SENSEX25O0984600PE': 223549189, 'SENSEX25O0984600CE': 223554053, 'SENSEX25O0984500PE': 223518981, 'SENSEX25O0984500CE': 223567621, 'SENSEX25O0984400PE': 223492101, 'SENSEX25O0984400CE': 223534085, 'SENSEX25O0984300PE': 223501573, 'SENSEX25O0984300CE': 223545861, 'SENSEX25O0984200CE': 223516421, 'SENSEX25O0984200PE': 223566341, 'SENSEX25O0984100PE': 223484677, 'SENSEX25O0984100CE': 223489029, 'SENSEX25O0984000CE': 223498501, 'SENSEX25O0984000PE': 223543557, 'SENSEX25O0983900CE': 223488517, 'SENSEX25O0983900PE': 223531013, 'SENSEX25O0983800PE': 223542277, 'SENSEX25O0983800CE': 223547653, 'SENSEX25O0983700PE': 223514117, 'SENSEX25O0983700CE': 223561221, 'SENSEX25O0983600PE': 223486725, 'SENSEX25O0983600CE': 223528453, 'SENSEX25O0983500PE': 223495173, 'SENSEX25O0983500CE': 223538693, 'SENSEX25O0983400CE': 223510533, 'SENSEX25O0983400PE': 223559685, 'SENSEX25O0983300PE': 223478021, 'SENSEX25O0983300CE': 223482373, 'SENSEX25O0983200CE': 223493125, 'SENSEX25O0983200PE': 223537669, 'SENSEX25O0983100PE': 223509253, 'SENSEX25O0983100CE': 223554309, 'SENSEX25O0983000PE': 223519237, 'SENSEX25O0983000CE': 223567877, 'SENSEX25O0982900PE': 223508485, 'SENSEX25O0982900CE': 223553541, 'SENSEX25O0982800PE': 223479813, 'SENSEX25O0982800CE': 223522565, 'SENSEX25O0982700PE': 223491077, 'SENSEX25O0982700CE': 223533573, 'SENSEX25O0982600CE': 223505413, 'SENSEX25O0981000CE': 223476229, 'SENSEX25O0981000PE': 223521285, 'SENSEX25O0980900PE': 223550469, 'SENSEX25O0980900CE': 223556357, 'SENSEX25O0980800CE': 223475205, 'SENSEX25O0980800PE': 223520261, 'SENSEX25O0980700PE': 223492613, 'SENSEX25O0980700CE': 223535109, 'SENSEX25O0980600PE': 223502341, 'SENSEX25O0980600CE': 223547141, 'SENSEX25O0980500CE': 223517445, 'SENSEX25O0980500PE': 223567365, 'SENSEX25O0980400PE': 223486469, 'SENSEX25O0980400CE': 223490053, 'SENSEX25O0980300CE': 223499525, 'SENSEX25O0980300PE': 223545349, 'SENSEX25O0980200PE': 223515909, 'SENSEX25O0980200CE': 223563781, 'SENSEX25O0980100CE': 223482117, 'SENSEX25O0980100PE': 223526149, 'SENSEX25O0980000PE': 223497733, 'SENSEX25O0980000CE': 223540997, 'SENSEX25O0979900CE': 223494661, 'SENSEX25O0979900PE': 223539973, 'SENSEX25O0979800CE': 223507205, 'SENSEX25O0979800PE': 223553029, 'SENSEX25O0979700CE': 223477253, 'SENSEX25O0979700PE': 223522053, 'SENSEX25O0979600PE': 223533061, 'SENSEX25O0979600CE': 223536901, 'SENSEX25O0979500PE': 223504901, 'SENSEX25O0979500CE': 223548933, 'SENSEX25O0979400PE': 223475461, 'SENSEX25O0979400CE': 223518725, 'SENSEX25O0979300PE': 223488005, 'SENSEX25O0979300CE': 223529733, 'SENSEX25O0979200CE': 223501317, 'SENSEX25O0979200PE': 223547397, 'SENSEX25O0979100CE': 223512325, 'SENSEX25O0979100PE': 223560965, 'SENSEX25O0979000CE': 223484421, 'SENSEX25O0979000PE': 223527941, 'SENSEX25O0978900PE': 223516677, 'SENSEX25O0978900CE': 223565317, 'SENSEX25O0978800PE': 223527173, 'SENSEX25O0978800CE': 223530757, 'SENSEX25O0978700PE': 223498757, 'SENSEX25O0978700CE': 223542021, 'SENSEX25O0978600CE': 223513861, 'SENSEX25O0978600PE': 223562757, 'SENSEX25O0978500PE': 223481349, 'SENSEX25O0978500CE': 223523845, 'SENSEX25O0978400CE': 223494917, 'SENSEX25O0978400PE': 223540229, 'SENSEX25O0978300PE': 223553285, 'SENSEX25O0978300CE': 223559429, 'SENSEX25O0978200CE': 223477765, 'SENSEX25O0978200PE': 223522309, 'SENSEX25O0978100PE': 223533317, 'SENSEX25O0978100CE': 223537413, 'SENSEX25O0978000PE': 223505157, 'SENSEX25O0978000CE': 223549445, 'SENSEX25O0977900PE': 223493381, 'SENSEX25O0977900CE': 223536133, 'SENSEX25O0977800CE': 223508229, 'SENSEX25O0977800PE': 223555333, 'SENSEX25O0977700CE': 223518213, 'SENSEX25O0977700PE': 223568901, 'SENSEX25O0977600CE': 223490821, 'SENSEX25O0977600PE': 223534597, 'SENSEX25O0977500PE': 223546629, 'SENSEX25O0977500CE': 223550725, 'SENSEX25O0977400PE': 223516933, 'SENSEX25O0977400CE': 223565573, 'SENSEX25O0977300PE': 223489541, 'SENSEX25O0977300CE': 223531269, 'SENSEX25O0977200PE': 223499013, 'SENSEX25O0977200CE': 223542533, 'SENSEX25O0977100CE': 223514373, 'SENSEX25O0977100PE': 223563013, 'SENSEX25O0977000PE': 223481605, 'SENSEX25O0977000CE': 223524101, 'SENSEX25O0976900CE': 223513349, 'SENSEX25O0976900PE': 223562245, 'SENSEX25O0976800CE': 223485701, 'SENSEX25O0976800PE': 223528965, 'SENSEX25O0976700PE': 223539461, 'SENSEX25O0976700CE': 223544581, 'SENSEX25O0976600PE': 223511557, 'SENSEX25O0976600CE': 223558405}

DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223511557/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223544581/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223539461/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223485701/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223528965/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223513349/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223562245/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223524101/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223481605/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223514373/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223563013/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223542533/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223499013/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223531269/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223489541/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223565573/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223516933/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223550725/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223546629/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223490821/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223534597/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223518213/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223568901/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223508229/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223555333/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223536133/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223493381/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223549445/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223505157/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223537413/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223533317/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223477765/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223522309/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223559429/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223553285/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223494917/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223540229/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223523845/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223481349/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223513861/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223562757/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223542021/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223498757/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223530757/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223527173/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223565317/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223516677/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223484421/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223527941/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223512325/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223560965/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223501317/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223547397/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223529733/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223488005/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223518725/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223475461/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223548933/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223504901/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223536901/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223533061/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223477253/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223522053/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223507205/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223553029/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223494661/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/223539973/15minute?from=2025-09-25+09%3A15%3A00&to=2025-10-09+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443

Added SENSEX values as a column to options dataframe.

Total option trading symbols generated: 202
Total mapped tokens found: 202
Historical rows fetched for options: 28863
Sample quotes fetched: 5

In [257]:
## SENSEX - Weekly - 15min

start = datetime(2025, 9, 4, 9, 15)
end = datetime(2025, 9, 18, 15, 45)
index = "SENSEX"
expiry_type = "weekly"
expiry = datetime(2025, 9, 18)
interval = "15minute"

# For SENSEX
open, ltp, atm_strike, token_map, option_hist_df, quotes_df  = fetch_index_options_weekly_data(kite, index, start, end, expiry,interval)

expiry1_date = expiry.strftime("%Y%m%d")
with pd.ExcelWriter(f'{index}_{expiry_type}_{interval}_{expiry1_date}.xlsx') as writer:
    option_hist_df.to_excel(writer, sheet_name='option_history', index=False)
    quotes_df.to_excel(writer, sheet_name='quotes', index=False)

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/265/day?from=2025-09-04+09%3A15%3A00&to=2025-09-04+09%3A15%3A00&interval=day&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /quote?i=BSE%3ASENSEX HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/BFO HTTP/1.1" 200 68053

---
Current SENSEX LTP: 83013.96
SENSEX Open on 2025-09-04: 81456
ATM Strike: 81500

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443

Mapped Options Tokens:
{'SENSEX2591882700CE': 220750085, 'SENSEX2591882700PE': 220780549, 'SENSEX2591882600PE': 220738309, 'SENSEX2591882600CE': 220784133, 'SENSEX2591882800CE': 220717061, 'SENSEX2591882800PE': 220746245, 'SENSEX2591882500CE': 220743173, 'SENSEX2591882500PE': 220773637, 'SENSEX2591882900CE': 220758789, 'SENSEX2591882900PE': 220789253, 'SENSEX2591882400CE': 220776709, 'SENSEX2591882400PE': 220806405, 'SENSEX2591883000CE': 220701445, 'SENSEX2591883000PE': 220731141, 'SENSEX2591882300CE': 220733701, 'SENSEX2591882300PE': 220762373, 'SENSEX2591883100PE': 220698629, 'SENSEX2591883100CE': 220806661, 'SENSEX2591882200CE': 220767749, 'SENSEX2591882200PE': 220797189, 'SENSEX2591883200CE': 220711429, 'SENSEX2591883200PE': 220741381, 'SENSEX2591882100PE': 220752645, 'SENSEX2591882100CE': 220802309, 'SENSEX2591883300CE': 220678405, 'SENSEX2591883300PE': 220706565, 'SENSEX2591882000CE': 220756997, 'SENSEX2591882000PE': 220787461, 'SENSEX2591883400PE': 220675077, 'SENSEX2591883400CE': 220720645, 'SENSEX2591883500PE': 220715525, 'SENSEX2591886500CE': 220716805, 'SENSEX2591886500PE': 220745733, 'SENSEX2591886400CE': 220748805, 'SENSEX2591886400PE': 220779269, 'SENSEX2591886300PE': 220737541, 'SENSEX2591886300CE': 220783109, 'SENSEX2591886200CE': 220742405, 'SENSEX2591886200PE': 220771589, 'SENSEX2591886100CE': 220775685, 'SENSEX2591886100PE': 220804869, 'SENSEX2591886000CE': 220732933, 'SENSEX2591886000PE': 220760581, 'SENSEX2591885900PE': 220683525, 'SENSEX2591885900CE': 220790277, 'SENSEX2591885800CE': 220687877, 'SENSEX2591885800PE': 220715781, 'SENSEX2591885700PE': 220675333, 'SENSEX2591885700CE': 220781061, 'SENSEX2591885600CE': 220678661, 'SENSEX2591885600PE': 220706821, 'SENSEX2591885500CE': 220711685, 'SENSEX2591885500PE': 220802821, 'SENSEX2591885400PE': 220699141, 'SENSEX2591885400CE': 220806917, 'SENSEX2591885300CE': 220701701, 'SENSEX2591885300PE': 220731397, 'SENSEX2591885200PE': 220691205, 'SENSEX2591885200CE': 220798725, 'SENSEX2591885100CE': 220695301, 'SENSEX2591885100PE': 220722949, 'SENSEX2591885000PE': 220681989, 'SENSEX2591885000CE': 220727045, 'SENSEX2591884900CE': 220709381, 'SENSEX2591884900PE': 220738565, 'SENSEX2591884800CE': 220743685, 'SENSEX2591884800PE': 220773893, 'SENSEX2591884700PE': 220729093, 'SENSEX2591884700CE': 220776965, 'SENSEX2591884600CE': 220733957, 'SENSEX2591884600PE': 220762629, 'SENSEX2591884500CE': 220768005, 'SENSEX2591884500PE': 220797445, 'SENSEX2591884400CE': 220725253, 'SENSEX2591884400PE': 220752901, 'SENSEX2591884300CE': 220757253, 'SENSEX2591884300PE': 220787717, 'SENSEX2591884200PE': 220745477, 'SENSEX2591884200CE': 220792581, 'SENSEX2591884100CE': 220748549, 'SENSEX2591884100PE': 220779013, 'SENSEX2591884000PE': 220676101, 'SENSEX2591884000CE': 220782853, 'SENSEX2591883900CE': 220702725, 'SENSEX2591883900PE': 220793861, 'SENSEX2591883800PE': 220692229, 'SENSEX2591883800CE': 220800261, 'SENSEX2591883700CE': 220696581, 'SENSEX2591883700PE': 220724485, 'SENSEX2591883600PE': 220683269, 'SENSEX2591883600CE': 220790021, 'SENSEX2591883500CE': 220687621, 'SENSEX2591881900CE': 220679685, 'SENSEX2591881900PE': 220708101, 'SENSEX2591881800CE': 220712197, 'SENSEX2591881800PE': 220803589, 'SENSEX2591881700CE': 220672773, 'SENSEX2591881700PE': 220700165, 'SENSEX2591881600CE': 220702469, 'SENSEX2591881600PE': 220732677, 'SENSEX2591881500PE': 220691973, 'SENSEX2591881500CE': 220799749, 'SENSEX2591881400CE': 220696325, 'SENSEX2591881400PE': 220724229, 'SENSEX2591881300PE': 220683013, 'SENSEX2591881300CE': 220728069, 'SENSEX2591881200CE': 220687365, 'SENSEX2591881200PE': 220715269, 'SENSEX2591881100CE': 220720389, 'SENSEX2591881100PE': 220748037, 'SENSEX2591881000CE': 220678149, 'SENSEX2591881000PE': 220706309, 'SENSEX2591880900CE': 220734981, 'SENSEX2591880900PE': 220763909, 'SENSEX2591880800CE': 220769285, 'SENSEX2591880800PE': 220798469, 'SENSEX2591880700CE': 220725765, 'SENSEX2591880700PE': 220753413, 'SENSEX2591880600CE': 220758277, 'SENSEX2591880600PE': 220788741, 'SENSEX2591880500PE': 220745989, 'SENSEX2591880500CE': 220793605, 'SENSEX2591880400CE': 220749829, 'SENSEX2591880400PE': 220780293, 'SENSEX2591880300PE': 220677125, 'SENSEX2591880300CE': 220783877, 'SENSEX2591880200CE': 220742917, 'SENSEX2591880200PE': 220773381, 'SENSEX2591880100CE': 220776453, 'SENSEX2591880100PE': 220806149, 'SENSEX2591880000CE': 220733445, 'SENSEX2591880000PE': 220762117, 'SENSEX2591879900CE': 220761605, 'SENSEX2591879900PE': 220792069, 'SENSEX2591879800PE': 220689925, 'SENSEX2591879800CE': 220796677, 'SENSEX2591879700CE': 220694533, 'SENSEX2591879700PE': 220782341, 'SENSEX2591879600PE': 220680965, 'SENSEX2591879600CE': 220787205, 'SENSEX2591879500CE': 220685573, 'SENSEX2591879500PE': 220775173, 'SENSEX2591879400PE': 220673285, 'SENSEX2591879400CE': 220778757, 'SENSEX2591879300CE': 220675845, 'SENSEX2591879300PE': 220703749, 'SENSEX2591879200CE': 220771333, 'SENSEX2591879200PE': 220801285, 'SENSEX2591879100PE': 220697093, 'SENSEX2591879100CE': 220804613, 'SENSEX2591879000CE': 220700421, 'SENSEX2591879000PE': 220790789, 'SENSEX2591878900PE': 220710661, 'SENSEX2591878900CE': 220755717, 'SENSEX2591878800CE': 220715013, 'SENSEX2591878800PE': 220744965, 'SENSEX2591878700CE': 220747781, 'SENSEX2591878700PE': 220777989, 'SENSEX2591878600CE': 220705541, 'SENSEX2591878600PE': 220736773, 'SENSEX2591878500CE': 220740869, 'SENSEX2591878500PE': 220770565, 'SENSEX2591878400CE': 220698373, 'SENSEX2591878400PE': 220726277, 'SENSEX2591878300CE': 220730629, 'SENSEX2591878300PE': 220759301, 'SENSEX2591878200PE': 220718341, 'SENSEX2591878200CE': 220764933, 'SENSEX2591878100CE': 220722693, 'SENSEX2591878100PE': 220751109, 'SENSEX2591878000CE': 220754949, 'SENSEX2591878000PE': 220784901, 'SENSEX2591877900CE': 220676869, 'SENSEX2591877900PE': 220704517, 'SENSEX2591877800CE': 220772869, 'SENSEX2591877800PE': 220801797, 'SENSEX2591877700PE': 220697861, 'SENSEX2591877700CE': 220805893, 'SENSEX2591877600CE': 220761349, 'SENSEX2591877600PE': 220791813, 'SENSEX2591877500PE': 220689669, 'SENSEX2591877500CE': 220796421, 'SENSEX2591877400CE': 220694277, 'SENSEX2591877400PE': 220781829, 'SENSEX2591877300PE': 220680709, 'SENSEX2591877300CE': 220786949, 'SENSEX2591877200CE': 220685317, 'SENSEX2591877200PE': 220712709, 'SENSEX2591877100PE': 220673029, 'SENSEX2591877100CE': 220778501, 'SENSEX2591877000CE': 220675589, 'SENSEX2591877000PE': 220703493, 'SENSEX2591876900CE': 220732421, 'SENSEX2591876900PE': 220760069, 'SENSEX2591876800CE': 220691717, 'SENSEX2591876800PE': 220719365, 'SENSEX2591876700CE': 220723973, 'SENSEX2591876700PE': 220751877, 'SENSEX2591876600PE': 220710405, 'SENSEX2591876600CE': 220755461, 'SENSEX2591876500CE': 220714757, 'SENSEX2591876500PE': 220744709}

DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220714757/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220744709/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220755461/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220710405/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220723973/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220751877/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220691717/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220719365/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220732421/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220760069/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220675589/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220703493/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220778501/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220673029/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220685317/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220712709/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220786949/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220680709/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220694277/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220781829/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220796421/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220689669/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220761349/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220791813/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220805893/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220697861/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220772869/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220801797/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220676869/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220704517/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220754949/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220784901/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220722693/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220751109/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220764933/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220718341/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220730629/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220759301/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220698373/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220726277/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220740869/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220770565/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220705541/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220736773/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220747781/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220777989/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220715013/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220744965/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220755717/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220710661/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220700421/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220790789/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220804613/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220697093/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220771333/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220801285/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220675845/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 46
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220703749/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220778757/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220673285/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220685573/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220775173/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220787205/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220680965/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220694533/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220782341/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/220796677/15minute?from=2025-09-04+09%3A15%3A00&to=2025-09-18+15%3A45%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443

Added SENSEX values as a column to options dataframe.

Total option trading symbols generated: 202
Total mapped tokens found: 202
Historical rows fetched for options: 30116
Sample quotes fetched: 5

In [14]:
def fetch_index_options_data_monthly_expiry(kite, index_symbol, start_date, end_date, expiry_date, interval="day", step=None):
    """
    Fetch index historical data (NIFTY 50 or SENSEX), determine ATM strike,
    generate option trading symbols for a given expiry, map them to instrument tokens,
    fetch their historical data, and get latest quotes.

    Parameters
    ----------
    kite : KiteConnect
        Initialized Kite Connect API client instance.
    index_symbol : str
        "SENSEX" or "NIFTY 50".
    start_date : datetime
        Start datetime for historical data.
    end_date : datetime
        End datetime for options historical data.
    expiry_date : datetime
        Expiry date for options trading symbols.
    interval : str, default "day"
        Candle interval for index historical data.
    step : int, optional
        Strike step size (default: 100 for Sensex, 50 for Nifty).

    Returns
    -------
    index_open : int
    index_ltp : float
    atm_strike : int
    token_map : dict
    all_hist_df : DataFrame
    quotes_df : DataFrame
    """

    # ----------------
    #  INDEX METADATA
    # ----------------
    index_map = {
        "SENSEX": {"token": 265, "exchange": "BSE", "step": 100, "opt_segment": "BFO"},
        "NIFTY 50": {"token": 256265, "exchange": "NSE", "step": 50, "opt_segment": "NFO"}
    }

    if index_symbol.upper() not in [key.upper() for key in index_map.keys()]:
        raise ValueError("Invalid index symbol. Use 'SENSEX' or 'NIFTY 50'")

    # Pick correct config
    for k, v in index_map.items():
        if k.upper() == index_symbol.upper():
            index_cfg = v
            index_symbol_std = k  # Standardized case
            break

    if step is None:
        step = index_cfg["step"]

    # ----------------
    # 1. Fetch Index Historical Data
    # ----------------
    hist = kite.historical_data(index_cfg["token"], start_date, start_date, interval="day")
    df_hist = pd.DataFrame(hist)
    df_hist['date'] = pd.to_datetime(df_hist['date'])
    index_open = int(df_hist['open'][0])

    # LTP of index
    full_symbol = f"{index_cfg['exchange']}:{index_symbol_std}"
    index_ltp = kite.quote(full_symbol)[full_symbol]['last_price']

    print("\n---")
    print(f"Current {index_symbol_std} LTP: {index_ltp}")
    print(f"{index_symbol_std} Open on {start_date.date()}: {index_open}")

    # ----------------
    # 2. ATM Calculation
    # ----------------
    atm_strike = int(round(index_open / step) * step)
    print(f"ATM Strike: {atm_strike}")

    # Strike Range
    strike_range = [atm_strike + i * step for i in range(-10, 11)]

    # ----------------
    # 3. Expiry String & Trading Symbols
    #    Exchange code format is different for NSE vs BSE
    # ----------------
    expiry_str_bse = f"{expiry_date.year % 100}{expiry_date.strftime('%b').upper()}"  # e.g., 25AUG
    expiry_str_nse = f"{expiry_date.year % 100}{expiry_date.strftime('%b').upper()}"  # e.g., 25AUG

    trading_symbols = []
    for strike in strike_range:
        if index_cfg['exchange'] == 'BSE':  # SENSEX
            if strike < atm_strike:
                trading_symbols.append(f"{index_symbol_std}{expiry_str_bse}{strike}PE")
            elif strike > atm_strike:
                trading_symbols.append(f"{index_symbol_std}{expiry_str_bse}{strike}CE")
        else:  # NSE (NIFTY)
            # Force "NIFTY" instead of NIFTY50
            nse_opts_symbol_prefix = "NIFTY" if "NIFTY" in index_symbol_std.upper() else index_symbol_std.replace(' ', '')
            if strike < atm_strike:
                trading_symbols.append(f"{nse_opts_symbol_prefix}{expiry_str_nse}{strike}PE")
            elif strike > atm_strike:
                trading_symbols.append(f"{nse_opts_symbol_prefix}{expiry_str_nse}{strike}CE")

    # ----------------
    # 4. Map to Tokens
    # ----------------
    try:
        instruments_df = pd.DataFrame(kite.instruments(index_cfg["opt_segment"]))
        index_ops = instruments_df[
            (instruments_df['exchange'] == index_cfg["opt_segment"]) &
            (instruments_df['segment'] == f"{index_cfg['opt_segment']}-OPT") &
            (instruments_df['tradingsymbol'].isin(trading_symbols)) &
            (instruments_df['expiry'] == expiry_date.date())
        ]
        
        token_map = {
            row['tradingsymbol']: row['instrument_token']
            for _, row in index_ops.iterrows()
        }
        print("\nMapped Options Tokens:")
        print(token_map)
    except Exception as e:
        print("\nCould not fetch instruments or no options available.")
        print(str(e))
        token_map = {}

    # ----------------
    # 5. Historical Data for Options
    # ----------------
    market_close_time = time(15, 30)  # 3:30 PM IST
    if start_date.date() == end_date.date():
        if end_date.time() > market_close_time:
            end_date = datetime.combine(end_date.date(), market_close_time)

    all_hist_df = pd.DataFrame()
    for symbol, token in {s: token_map.get(s) for s in trading_symbols}.items():
        if token:
            try:
                hist = kite.historical_data(token, start_date, end_date, interval=interval)
                df_hist = pd.DataFrame(hist)
                df_hist["symbol"] = symbol
                df_hist["token"] = token
                all_hist_df = pd.concat([all_hist_df, df_hist], ignore_index=True)
            except Exception as e:
                print(f"Error fetching data for {symbol}: {e}")
        else:
            print(f"Token not found for {symbol}")

    # For intraday, filter out candles after market close (3:30 PM IST)
        all_hist_df['date'] = pd.to_datetime(all_hist_df['date'])
        market_close_time = time(15, 30)
        all_hist_df = all_hist_df[all_hist_df['date'].dt.time <= market_close_time]

    # ----------------
    # 6. Latest Quotes (Sample)
    # ----------------
    token_map_sample = dict(list(token_map.items())[:5])
    tokens = list(token_map_sample.values())
    if tokens:
        quotes = kite.quote(tokens)
        quotes_df = pd.DataFrame([
            {"symbol": sym, "token": tok, **quotes[str(tok)]}
            for sym, tok in token_map_sample.items()
        ])
    else:
        quotes_df = pd.DataFrame()

    # ----------------
    # 7. Summary
    # ----------------
    print(f"\nTotal option trading symbols generated: {len(trading_symbols)}")
    print(f"Total mapped tokens found: {len(token_map)}")
    print(f"Historical rows fetched for options: {len(all_hist_df)}")
    print(f"Sample quotes fetched: {len(quotes_df)}")

    return index_open, index_ltp, atm_strike, token_map, all_hist_df, quotes_df

In [28]:
# SENSEX

start = datetime(2025, 7, 29, 9, 15)
end = datetime(2025, 8, 26, 15, 30)

sensex_expiry = datetime(2025, 8, 26)

# For SENSEX
#sensex_results 
sensex_open, sensex_ltp, sn_atm_strike, sn_token_map, sn_option_hist_df, sn_quotes_df = fetch_index_options_data_monthly_expiry(kite, "SENSEX", start, end, sensex_expiry, interval="15minute")

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/265/day?from=2025-07-29+09%3A15%3A00&to=2025-07-29+09%3A15%3A00&interval=day&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /quote?i=BSE%3ASENSEX HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/BFO HTTP/1.1" 200 62398

---
Current SENSEX LTP: 80786.54
SENSEX Open on 2025-07-29: 80620
ATM Strike: 80600

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211706629/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443

Mapped Options Tokens:
{'SENSEX25AUG81600CE': 211607813, 'SENSEX25AUG81500CE': 211671301, 'SENSEX25AUG81400CE': 211737861, 'SENSEX25AUG81300CE': 211656197, 'SENSEX25AUG81200CE': 211721733, 'SENSEX25AUG81100CE': 211637765, 'SENSEX25AUG81000CE': 211703045, 'SENSEX25AUG80900CE': 211816453, 'SENSEX25AUG80800CE': 211732485, 'SENSEX25AUG80700CE': 211796229, 'SENSEX25AUG80500PE': 211569157, 'SENSEX25AUG80400PE': 211636229, 'SENSEX25AUG80300PE': 211824645, 'SENSEX25AUG80200PE': 211619589, 'SENSEX25AUG80100PE': 211803909, 'SENSEX25AUG80000PE': 211603717, 'SENSEX25AUG79900PE': 211659781, 'SENSEX25AUG79800PE': 211573509, 'SENSEX25AUG79700PE': 211641605, 'SENSEX25AUG79600PE': 211706629}

DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211641605/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211573509/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211659781/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211603717/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211803909/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211619589/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211824645/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211636229/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211569157/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211796229/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211732485/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211816453/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211703045/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211637765/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211721733/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211656197/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211737861/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211671301/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/211607813/15minute?from=2025-07-29+09%3A15%3A00&to=2025-08-26+15%3A30%3A00&interval=15minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /quote?i=211607813&i=211671301&i=211737861&i=211656197&i=211721733 HTTP/1.1" 200 None

Total option trading symbols generated: 20
Total mapped tokens found: 20
Historical rows fetched for options: 9724
Sample quotes fetched: 5

### NIFTY Historical Data

In [64]:
def fetch_historical_data_batchwise(token, symbol, start_dt, end_dt, interval):
    combined_df = pd.DataFrame()
    delta_days = 100

    batch_start = start_dt
    while batch_start < end_dt:
        # Set batch tentative end
        batch_end_candidate = batch_start + timedelta(days=delta_days)
        
        # Adjust batch end
        if batch_end_candidate > end_dt:
            batch_end = end_dt
        else:
            batch_end = datetime.combine(batch_end_candidate.date(), time(15, 30))
            if batch_end > end_dt:
                batch_end = end_dt
        
        # Fetch data from Kite
        hist = kite.historical_data(token, batch_start, batch_end, interval)
        batch_df = pd.DataFrame(hist)

        # Add batch start/end columns
        batch_df["symbol"] = symbol
        #batch_df["token"] = token

        # Combine
        combined_df = pd.concat([combined_df, batch_df], ignore_index=True)

        # Next batch start: 9:15 next day
        next_day = batch_end.date() + timedelta(days=1)
        batch_start = datetime.combine(next_day, time(9, 15))
    
    return combined_df

In [65]:
# Inputs for NIFTY historical data
start = datetime(2024, 8, 29, 9, 15)
end = datetime(2025, 9, 30, 15, 45)
token = 256265
symbol = "NIFTY 50"
interval = "5minute"


# Fetch in batches
df_hist_nifty = fetch_historical_data_batchwise(token, symbol, start, end, interval)
display(df_hist_nifty)

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/256265/5minute?from=2024-08-29+09%3A15%3A00&to=2024-12-07+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/256265/5minute?from=2024-12-08+09%3A15%3A00&to=2025-03-18+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/256265/5minute?from=2025-03-19+09%3A15%3A00&to=2025-06-27+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/256265/5minute?from=2025-06-28+09%3A15%3A00&to=2025-09-30+15%3A45%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None

,date,open,high,low,close,volume,symbol
0,2024-08-29 09:15:00+05:30,25035.30,25045.70,25017.50,25029.00,0,NIFTY 50
1,2024-08-29 09:20:00+05:30,25029.60,25051.35,25027.50,25051.35,0,NIFTY 50
2,2024-08-29 09:25:00+05:30,25052.10,25073.65,25049.00,25054.25,0,NIFTY 50
3,2024-08-29 09:30:00+05:30,25054.85,25064.25,25043.85,25046.65,0,NIFTY 50
4,2024-08-29 09:35:00+05:30,25046.45,25063.90,25043.70,25054.30,0,NIFTY 50
...,...,...,...,...,...,...,...
20332,2025-09-30 15:05:00+05:30,24614.20,24617.95,24598.15,24610.65,0,NIFTY 50
20333,2025-09-30 15:10:00+05:30,24608.40,24615.85,24603.95,24614.85,0,NIFTY 50
20334,2025-09-30 15:15:00+05:30,24613.50,24614.75,24603.30,24607.40,0,NIFTY 50
20335,2025-09-30 15:20:00+05:30,24606.95,24613.70,24605.15,24611.85,0,NIFTY 50
20336,2025-09-30 15:25:00+05:30,24612.05,24634.90,24612.05,24633.60,0,NIFTY 50

In [66]:
df_hist_nifty['date'] = pd.to_datetime(df_hist_nifty['date']).dt.tz_localize(None)

df_hist_nifty

,date,open,high,low,close,volume,symbol
0,2024-08-29 09:15:00,25035.30,25045.70,25017.50,25029.00,0,NIFTY 50
1,2024-08-29 09:20:00,25029.60,25051.35,25027.50,25051.35,0,NIFTY 50
2,2024-08-29 09:25:00,25052.10,25073.65,25049.00,25054.25,0,NIFTY 50
3,2024-08-29 09:30:00,25054.85,25064.25,25043.85,25046.65,0,NIFTY 50
4,2024-08-29 09:35:00,25046.45,25063.90,25043.70,25054.30,0,NIFTY 50
...,...,...,...,...,...,...,...
20332,2025-09-30 15:05:00,24614.20,24617.95,24598.15,24610.65,0,NIFTY 50
20333,2025-09-30 15:10:00,24608.40,24615.85,24603.95,24614.85,0,NIFTY 50
20334,2025-09-30 15:15:00,24613.50,24614.75,24603.30,24607.40,0,NIFTY 50
20335,2025-09-30 15:20:00,24606.95,24613.70,24605.15,24611.85,0,NIFTY 50
20336,2025-09-30 15:25:00,24612.05,24634.90,24612.05,24633.60,0,NIFTY 50

In [67]:
df_hist_nifty.to_csv("nifty_historical_data_sep_24-sep_25_5min.csv", index=False)

In [36]:
# Inputs for SENSEX historical data
start = datetime(2023, 1, 1, 9, 15)
end = datetime(2025, 8, 14, 15, 30)
token = 265
symbol = "SENSEX"
interval = "5minute"


# Fetch in batches
df_hist_sensex = fetch_historical_data_batchwise(token, symbol, start, end, interval)
display(df_hist_sensex)

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/265/5minute?from=2023-01-01+09%3A15%3A00&to=2023-04-11+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/265/5minute?from=2023-04-12+09%3A15%3A00&to=2023-07-21+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/265/5minute?from=2023-07-22+09%3A15%3A00&to=2023-10-30+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/265/5minute?from=2023-10-31+09%3A15%3A00&to=2024-02-08+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/265/5minute?from=2024-02-09+09%3A15%3A00&to=2024-05-19+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/265/5minute?from=2024-05-20+09%3A15%3A00&to=2024-08-28+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/265/5minute?from=2024-08-29+09%3A15%3A00&to=2024-12-07+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/265/5minute?from=2024-12-08+09%3A15%3A00&to=2025-03-18+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/265/5minute?from=2025-03-19+09%3A15%3A00&to=2025-06-27+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.kite.trade:443
DEBUG:urllib3.connectionpool:https://api.kite.trade:443 "GET /instruments/historical/265/5minute?from=2025-06-28+09%3A15%3A00&to=2025-08-14+15%3A30%3A00&interval=5minute&continuous=0&oi=0 HTTP/1.1" 200 None

,date,open,high,low,close,volume,symbol,token
0,2023-01-02 09:15:00+05:30,60871.24,60963.11,60853.18,60853.18,0,SENSEX,265
1,2023-01-02 09:20:00+05:30,60855.77,60925.84,60789.96,60919.41,0,SENSEX,265
2,2023-01-02 09:25:00+05:30,60916.24,60926.41,60788.91,60809.55,0,SENSEX,265
3,2023-01-02 09:30:00+05:30,60806.23,60900.86,60765.02,60884.40,0,SENSEX,265
4,2023-01-02 09:35:00+05:30,60879.63,60978.47,60866.03,60978.47,0,SENSEX,265
...,...,...,...,...,...,...,...,...
48583,2025-08-14 15:05:00+05:30,80627.51,80651.66,80609.41,80625.36,0,SENSEX,265
48584,2025-08-14 15:10:00+05:30,80624.59,80641.72,80597.08,80597.25,0,SENSEX,265
48585,2025-08-14 15:15:00+05:30,80595.27,80618.40,80574.04,80597.97,0,SENSEX,265
48586,2025-08-14 15:20:00+05:30,80594.78,80618.07,80562.81,80593.07,0,SENSEX,265
48587,2025-08-14 15:25:00+05:30,80592.35,80594.47,80533.61,80547.36,0,SENSEX,265

In [37]:
# Convert 'date' column to datetime and remove timezone information
df_hist_nifty['date'] = pd.to_datetime(df_hist_nifty['date']).dt.tz_localize(None)
df_hist_sensex['date'] = pd.to_datetime(df_hist_sensex['date']).dt.tz_localize(None)

df_hist_nifty.to_excel("nifty_historical_data_23-25_5min.xlsx", index=False)
df_hist_sensex.to_excel("sensex_historical_data_23-25_5min.xlsx", index=False)

In [ ]:
def feature_engineering_nifty(df):
    df = df.copy()
    # Parse datetime and set as index
    df['date'] = pd.to_datetime(df['date'])
    df = df.sort_values('date')
    df.set_index('date', inplace=True)

    # Time-based features
    df['hour'] = df.index.hour
    df['minute'] = df.index.minute

    # Price action features
    df['typical_price'] = (df['high'] + df['low'] + df['close']) / 3
    df['price_range'] = df['high'] - df['low']
    df['return'] = df['close'].pct_change()

    # Lag features
    for lag in range(1, 6):
        df[f'close_lag_{lag}'] = df['close'].shift(lag)
        df[f'return_lag_{lag}'] = df['return'].shift(lag)

    # Rolling volatility
    df['volatility_15'] = df['return'].rolling(window=15).std()

    # Expiry day composite features (NSE expiry is last Thursday monthly)
    df['weekday'] = df.index
    df['month'] = df.index.month
    df['year'] = df.index.year

    # Find last Thursdays
    last_thursdays = []
    for year in df['year'].unique():
        for month in df[df['year'] == year]['month'].unique():
            temp = df[(df['year'] == year) & (df['month'] == month)]
            thursdays = temp[temp['weekday'] == 3].index.floor('D').unique()
            if len(thursdays): last_thursdays.append(thursdays[-1])

    df['expiry_day'] = df.index.floor('D').isin(last_thursdays).astype(int)
    df['day_category'] = 'other_days'
    for expiry in last_thursdays:
        prev = expiry - pd.Timedelta(days=1)
        df.loc[df.index.floor('D') == expiry, 'day_category'] = 'expiry_day'
        df.loc[df.index.floor('D') == prev, 'day_category'] = 'previous_day'

    # Last 2 hours flag (market close usually 15:30 IST)
    df['minutes_since_open'] = (df.index.hour - 9) * 60 + df.index.minute
    market_close_minutes = 15*60 + 30
    df['last_2_hours'] = ((df['minutes_since_open'] >= market_close_minutes - 120) & 
                          (df['minutes_since_open'] <= market_close_minutes)).astype(int)
    return df

In [495]:
# Usage:
df1_hist_nifty = feature_engineering_nifty(df_hist_nifty)

In [489]:
df1_hist_nifty.columns

Index(['open', 'high', 'low', 'close', 'volume', 'symbol', 'token', 'hour',
       'minute', 'typical_price', 'price_range', 'return', 'close_lag_1',
       'return_lag_1', 'close_lag_2', 'return_lag_2', 'close_lag_3',
       'return_lag_3', 'close_lag_4', 'return_lag_4', 'close_lag_5',
       'return_lag_5', 'volatility_15', 'weekday', 'month', 'year',
       'expiry_day', 'day_category', 'minutes_since_open', 'last_2_hours'],
      dtype='object')

In [497]:
df1_hist_nifty[[ 'price_range', 'return', 'close_lag_1','weekday',
       'return_lag_1', 'close_lag_2', 'return_lag_2', 'close_lag_3',
       'return_lag_3', 'close_lag_4', 'return_lag_4', 'close_lag_5',
       'return_lag_5', 'volatility_15', 'weekday', 'month', 'year',
       'expiry_day', 'day_category', 'minutes_since_open', 'last_2_hours']].head()

,price_range,return,close_lag_1,weekday,return_lag_1,close_lag_2,return_lag_2,close_lag_3,return_lag_3,close_lag_4,...,close_lag_5,return_lag_5,volatility_15,weekday,month,year,expiry_day,day_category,minutes_since_open,last_2_hours
date,,,,,,,,,,,,,,,,,,,,,
2024-01-01 09:15:00,52.60,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0,1,2024,0,other_days,15,0
2024-01-01 09:30:00,27.85,0.000242,21700.80,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0,1,2024,0,other_days,30,0
2024-01-01 09:45:00,34.35,0.000933,21706.05,0,0.000242,21700.80,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0,1,2024,0,other_days,45,0
2024-01-01 10:00:00,29.05,-0.000766,21726.30,0,0.000933,21706.05,0.000242,21700.80,NaN,NaN,...,NaN,NaN,NaN,0,1,2024,0,other_days,60,0
2024-01-01 10:15:00,24.30,0.000131,21709.65,0,-0.000766,21726.30,0.000933,21706.05,0.000242,21700.8,...,NaN,NaN,NaN,0,1,2024,0,other_days,75,0